### ISSUE TITLE
Move widgets to other dashboards

### ISSUE THREAD

**Issue by dominicdesu** [openhab/org.openhab.ui.habpanel#10]
Would be nice in my opinion if one could move widgets from one dashboard to another. If one dashboard grows to large and I decide to create a seperate dashboard, I would certainly like to move my existing widgets instead of creating them anew in the new dashboard.
Maybe this functionality can be combined with the copy functionality mentioned in #9?
##

**Comment by ghys** [comment]
I thought about this too, yes. It makes sense.

**Comment by isigmund** [comment]
I did start working on this enhancement. It will allow to copy widgets on the same dashboard and copy/move widgets to another dashboard. I think deleting a widget should be possible without having to go to the settings.
I envision "footer buttons" on each widget when the dashboard is in edit mode. It will look like this:
![image](https://cloud.githubusercontent.com/assets/5901482/19832080/9f83fbc2-9e1a-11e6-8924-ffd281d2e661.png)
Any comments or suggestions are welcome ....

**Comment by ghys** [comment]
Sorry, no more icons on the widget placeholder - this was a decision I made even before the first version was published (it had a delete icon). When the widget's resized too small they overlap and it becomes hard to use with a touch device.
I actually think the Delete button is fine in the settings dialog, where can't be clicked by accident. I intended to put the Clone button/dropdown there too.
A dropdown menu on the top-right corner (replacing glyphicon-cog with glyphicon-option-vertical) would also be an acceptable solution.

**Comment by isigmund** [comment]
Fair enough, I like the dropdown menu idea as well. I will adapt what I already have and post some screenshots to discuss again.

**Comment by isigmund** [comment]
Ok - made the chaages. It does look like this now:
![image](https://cloud.githubusercontent.com/assets/5901482/19835880/ae29644c-9e91-11e6-9081-4bdf826e15d1.png)
I really like it that way. Do you prefer the dropdown entries with or without an additional icon?

There is one issue though. There can be situations where he dropdown is showing behind another placeholder widget:
![image](https://cloud.githubusercontent.com/assets/5901482/19835905/2f34b6d6-9e92-11e6-9cad-6e3c93328407.png)
I tried playing with the z-order but that does only effect the z-Order of one placeholder and not absolute to all other placeholders. Do you have an idea how this can be avoided ?

**Comment by ghys** [comment]
I like it as well. I believe you can use dropdown-append-to-body now and it will solve your problem.
As for icons in the menu - why not, that could look nicer. Labels should be named "Copy to..." and "Move to..." to signal they'll be expecting another location.
Also, how do you intend to select the target dashboard? A simple second menu level could do the trick maybe?

**Comment by isigmund** [comment]
I will do the text changes and add icons. To select the copy/move target I have so far an modal dialog with a dropdown or select th dashboard, but the 2nd menu level is also good idea.
But first I need to investigate that layering issue a bit more, just adding dropdown-append-to-body does not work. If I add that the dropdown does not open at all. At the moment I believe it's really the version of angular-bootstrap that doesn't support this yet. But as I said I will investigate some more....

**Comment by isigmund** [comment]
@ghys I got the layering issue sorted out. The dropdown-append-to-body works now.

I played a bit with a submenu to select the target dashboard for the copy/move operations. To does look like this:
![image](https://cloud.githubusercontent.com/assets/5901482/19888540/819f5522-a02f-11e6-809f-ad92c15c3d39.png)
The copy submenu would contain all dashboards (including the one that is currently edited) and the move submenu would contain all dashoards except the current one.
The submenu might be not optimal for a touch device but it does work there as well. Its just not a common pattern for a touch UI.

The other option is to use a modal to decide the target dashboard. It could look like this:
![image](https://cloud.githubusercontent.com/assets/5901482/19888614/09ac5e1a-a030-11e6-9a29-e335ad4f125b.png)

I leave it up to you to decide which route to go. Just let me know .....

**Comment by ghys** [comment]
You're right, in the end I think I prefer the modal dialog as well. It would be nice if angular-modal could be used for simplicity, but I think it has problems with its dropdown selection feature... could be wrong though.
Also maybe combine the menu items (Copy/move to...) and add another button in the modal (Cancel, Move, Copy)?

**Comment by isigmund** [comment]
Ok I combinded copy and move into one menu item:
![image](https://cloud.githubusercontent.com/assets/5901482/19943283/fbdf618a-a136-11e6-9a4c-243a9a6a5f14.png)

The move button on the modal is disabled when you select the current dashboard as target since moving to the same dashboard does not make sense:
![image](https://cloud.githubusercontent.com/assets/5901482/19943350/4f7aa7fa-a137-11e6-8415-26b0d7ec961a.png)

If you are ok with it, I will rebase from master, since I saw you commited a couple of things, and then create a PR, but I wait for your ok or further comments.

Take care
   Ingo

**Comment by ghys** [comment]
Great, looks good!
Thanks for your work.
