### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by thib5** [openhab/org.openhab.ui.habpanel#100]
Is it possible to Edit the theme ?  I can't find the fine in my openhab 2 folder

**Comment by kubawolanin** [comment]
Please read [contributing guidelines](https://github.com/openhab/org.openhab.ui.habpanel/blob/master/CONTRIBUTING.md) first.
Here's @ghys's commit message that explains [how to contribute a new theme to the project](https://github.com/openhab/org.openhab.ui.habpanel/commit/c98d2b20934a31d151bf4aada69bacc1ec08a94b).

When you'll have your development environment ready, copy existing [default theme](https://github.com/openhab/org.openhab.ui.habpanel/tree/master/web/assets/styles/themes/default)
and modify `_variables.less` file. You'd want to change `*.scss` and `*.min.css` file names as well.
After that please add your theme to the [themes.json file](https://github.com/openhab/org.openhab.ui.habpanel/blob/master/web/assets/styles/themes/themes.json).
