### ISSUE TITLE
Not including file changes and files in build enviroment 

### ISSUE THREAD

**Issue by Murpher** [openhab/org.openhab.ui.habpanel#103]
Hope this is in the right place.

I'm just getting myself familiar with the openHAB IDE and HABpanel.

I have the openHAB runtine working fine on localhost and have HABpanel working through this as a plugin.

I'm also able to follow the steps in the Contributing.md npm install etc and building a package using maven.

Issue I'm having is with gulp I think if I update say the slider.scss with new class, and run nvm,bower,gulp and run the new class is not included, also say if I include a new .scss file in the slider folder it's not included .
If you have any ideas or advice that would be great.

**Comment by Murpher** [comment]
Got it sorted!

After doing gulp and every letter combination. gulp sass is what I was missing.

**Comment by ghys** [comment]
The "sass" task should probably be run by default, yes, I know ;) Glad you figured it out.
