### ISSUE TITLE
Display item state using different icon (instead of color only)

### ISSUE THREAD

**Issue by gersilex** [openhab/org.openhab.ui.habpanel#105]
As **user**
I would like to have **different icons for the different item states**
so I can
- better see if a
-- door is open/closed
-- a lightbulb is on/off
-- the curtains are up/down

A/C: 
- Items with the Bulb icon use an icon with light rays, when the state is ON or 1-100%
- Items with the Door/Windows icon use an open/closed icon, matching the state
- State is invertable when configuring the widget
- Default icon is shown, if there are no distinct icons found

**Comment by ghys** [comment]
This is already supported when you use certain icons from the ["Eclipse SmartHome Classic" set](http://docs.openhab.org/addons/iconsets/classic/readme.html) (`blinds`, `lights`, `window` etc.), if there is a matching icon with a `-state` suffix the icon infrastructure will display it to match the item's state, instead the default icon will be used.

For instance, if you choose the `light` icon and the item state is 'on' or 'off', the `light-on` resp. `light-off` icon will be displayed.

**Comment by gersilex** [comment]
Thank you very much!

Yannick Schaus <notifications@github.com> schrieb am Mi., 28. Dez. 2016 um
19:49 Uhr:
