### ISSUE TITLE
Bug: Side-drawer layout corrupted

### ISSUE THREAD

**Issue by kubawolanin** [openhab/org.openhab.ui.habpanel#106]
When there's more Dashboards than fit on the screen, layout of the left-hand side drawer breaks:
![habpanel-bug](https://cloud.githubusercontent.com/assets/2270505/21571017/87278184-cecb-11e6-928b-df04881287e2.gif)

Steps to reproduce:
1. Make multiple dashboards so you have a scrollbar on the `aside` section.
2. Open the drawer
3. Scroll down

Expected results:
All dashboards are accessible and not covered by the black footer

Actual results:
Some of the dashboards on the list are covered.

**Comment by ghys** [comment]
noticed that too :)
But I don't really have a solution right now, the drawer doesn't seem to like `position: fixed` elements very much...
