### ISSUE TITLE
Labels and dividers on main dashboard

### ISSUE THREAD

**Issue by bruxi** [openhab/org.openhab.ui.habpanel#108]
Hi,
what about having the ability to place labels on the main dashboard? Also it would be nice having vertical and horizontal dividers not only on the main dashboard but on all.

Very nice work so far, HabPanel was the missing piece until now :-)

Best regards,
Jens

**Comment by gersilex** [comment]
Do you think the dividers should be between the tiles, or a tile itself?

IMHO it should be between the tiles but that would require a change in the tiling framework, I suppose.

**Comment by ghys** [comment]
#204, a new experimental feature, allows a custom widget to replace a standard tile on the main menu, thus allowing greater customizability, including borders and labels.
Separators can also be achieved with a custom widget, I don't think they will ever happen as a built-in feature 😦. Closing.
