### ISSUE TITLE
Status widget (with mapping) idea

### ISSUE THREAD

**Issue by mdilger** [openhab/org.openhab.ui.habpanel#11]
Currently I am using the dummy widget to show status of various items for example roller blinds and window actuators.

The issue I have is that I am getting different status data from openHAB 2 .   In the case of my Windows actuators, I initially get "DOWN" when I send an "DOWN" command, however after a refresh it goes to "100".  

I know that I could do this by rules in openHAB 2 , but it would be a really nice feature to have an in built mapping capability in the widget for 2 status conditions where you could test for 2 'openHAB' conditions per status.

It would also be good to be able to define a custom status message, therefore  3 text input fields per status condition would be needed.  

For example.

**Status condition 1 - Windows Open**

**Condition 1:**  DOWN **Condition 2**: 100  **Displayed Status:** Open
i.e. if the reported status from openHAB is either "DOWN" or "100" then the widget reports '"Open"

**Status condition 2 - Windows Closed**

**Condition 1:**  UP **Condition 2:** 0  **Displayed Status:** Closed 
i.e. if the reported status from openHAB is either "UP" or "0" then the widget reports "Closed"

In the case of my roller blinds I want to map "DOWN" and "100" to "Closed" and vice versa.

It would be great to have this flexibility at the widget level as I have 10 window actuators and 12 blind motors to control individually and these will also be under multiple groups for group control.

Taking this a little further it would be good if icons and colours were able to be changed for the 2 conditions, but this is not essential for my current needs.
##

**Comment by mdilger** [comment]
EDIT: some minor corrections made above.

**Comment by ghys** [comment]
Closing this because I believe it's now covered by the template widget.
