### ISSUE TITLE
Enhancement : Floating Speech Button

### ISSUE THREAD

**Issue by Murpher** [openhab/org.openhab.ui.habpanel#111]
Just due to the size of the speech comment button.  What do you guys think of making it possible to have it also as a floating style button as below.  

It's not going to be suited to all so possibly have a setting whether to display or not?

![image](https://cloud.githubusercontent.com/assets/5637583/21826440/5a729c3e-d77f-11e6-81cf-541fef59a1ca.jpg)

**Comment by kubawolanin** [comment]
I was thinking about it too.
Maybe it should be configurable in the settings panel.
@ghys what do you think?

**Comment by ghys** [comment]
Optional is a must since it covers a potential widget in the bottom right-hand corner.
Another possibility would be to make the speech recognition a potential "action type" of the Button widget (beside send command, navigate to dashboard and so on.) - that way it could be placed anywhere on a dashboard and could be configured (fonts, colors, icon) like a standard button.

**Comment by Murpher** [comment]
Been thinking about this one alot!! What suits everyone, Fully understand could cover a widget and still back at my reason for suggesting configuration in settings panel.

Two things on having it in a Button Widget.
1) If accessed on laptop the button would be visible in bottom right corner(if placed there) but if someone accessed on a mobile they would have to scroll to the bottom of the page before clicking.

2) Button styling would be in a container, even when checked off it is still in the .box class with a border shadow. Would it look as clean as designing it into the backend of HABPanel? (Still Possibly have color configuration,icon)

I got my idea from the google inbox app where the create new message is in a floating button on the bottom right corner.  It's there as you scroll up and down on the page making it always accessible.  If people are going to use voice commands you want to be able to call them quick rather then being able to scroll to the button,knob,slider first.

**Comment by kubawolanin** [comment]
FTR: I'm working on optional floating button feature described by @Murpher and I will implement new action type in Button widget as well (great idea @ghys by the way). Just started with this, so no ETA 🙂
