### ISSUE TITLE
Dashboard menucolumns not saved

### ISSUE THREAD

**Issue by AlleexxR** [openhab/org.openhab.ui.habpanel#112]
On saving a new config or an existing config in openHAB, then number of dashboard columns is always reset to 1. 
I suppose, the error ist in settings.controller starting at line 31. There only the dashboard an the updatedTime are set, not the number of columns. If I add `"menucolumns": $rootScope.menucolumns,` then everythings works as expected.

**Comment by ghys** [comment]
Good catch!
