### ISSUE TITLE
iframe doesn't work

### ISSUE THREAD

**Issue by tavalin** [openhab/org.openhab.ui.habpanel#12]
I'm trying to add an iframe to show a page from an external site but the widget remains blank.

I have tried the widget with multiple websites.  I have also tried visting the dashboard both inside my network and outside and the outcome is the same (i.e. blank widget).

**Comment by digiltd** [comment]
Hmmm, all working fine here. I cobbled together the iFrame widget for the panel. I was going to say that it might be because it was originally created for the original openhab.

![image](https://cloud.githubusercontent.com/assets/5680968/18517660/f8dc6f6e-7a94-11e6-90d7-97d8bc900988.png)

**Comment by tavalin** [comment]
@digiltd OK, I tried again with http://bbc.co.uk/news and it works.  Then I tried with a few other URLs and it didn't work.

![capture](https://cloud.githubusercontent.com/assets/1771518/18518040/586d03b6-7a96-11e6-87e7-cd2578282777.PNG)

Not sure what the issue is!

**Comment by digiltd** [comment]
Unfortunately you are at the mercy of the site you are trying to put in an iFrame. The developers can stop their site from being used in an iFrame. Widget or no widget :(

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by ghys** [comment]
Sam couldn't have said it better :)
