### ISSUE TITLE
Enhancement: ExternalScripts, getItem, and milliseconds option for image

### ISSUE THREAD

**Issue by LuckyMallari** [openhab/org.openhab.ui.habpanel#129]
My Changes: https://github.com/LuckyMallari/org.openhab.ui.habpanel

ExternalScripts:
Basically, it adds ../static/habpanel/externalscripts.js to head
Users can then create their own scripts (Angular or not) to their hearts' content.

getItem()
returns item (to access all properties)

Milliseconds:
Image $interval now has 2 options: seconds (default) or milliseconds.
Does not break existing install/configs.

**Comment by kubawolanin** [comment]
Adding #128 for reference.

**Comment by ghys** [comment]
>ExternalScripts:
>Basically, it adds ../static/habpanel/externalscripts.js to head
> Users can then create their own scripts (Angular or not) to their hearts' content.

Sorry, I don't agree with this solution. You can actually lazy load external resources using the ocLazyLoad directive (https://oclazyload.readme.io/docs/oclazyload-directive) but I'm now realizing there is a big security hole with this. I need to address this ASAP.

> getItem()
> returns item (to access all properties)

This is already covered by #114 which was submitted first.

> Milliseconds:
> Image $interval now has 2 options: seconds (default) or milliseconds.
> Does not break existing install/configs.

Can you please submit a separate PR for this?

Thank you!

**Comment by ghys** [comment]
> I need to address this ASAP.

Partial mitigation measure in #132 ...it's a shame it didn't make 2.0.0.

**Comment by LuckyMallari** [comment]
Closing issue. 
Opened a new PR here:
https://github.com/openhab/org.openhab.ui.habpanel/issues/133
