### ISSUE TITLE
Enhancement: Milliseconds support for image widget

### ISSUE THREAD

**Issue by LuckyMallari** [openhab/org.openhab.ui.habpanel#133]
Commit:
https://github.com/LuckyMallari/org.openhab.ui.habpanel/commit/9d46ec60975db4812785155352b86df4624084ca

Opening a new PR as requested here (now closed):
https://github.com/openhab/org.openhab.ui.habpanel/issues/129

Basically,  the current image widget is restricted to only use seconds for interval/duration. Adding a milliseconds options is helpful for those using the image widget for their webcam/security cameras. 

The code change considers previous install. It will default to seconds to not break existing configurations. Users can then modify their tiles and edit the image widget and change them to milliseconds if they desire.

Use case:
I have 16 security cameras. I want X number of cameras to refresh every 1 second, and Y number of ("critical") cameras to refresh every 100 ms (10 fps). 

![image](https://cloud.githubusercontent.com/assets/6183345/22226485/84117fd2-e17b-11e6-9ba9-4e8446af6895.png)

**Comment by ghys** [comment]
Closed by #128.
