### ISSUE TITLE
Chart secondary axis wrong when first axis is not autoscaling

### ISSUE THREAD

**Issue by HaukeRa** [openhab/org.openhab.ui.habpanel#134]
When setting fixed limits on the first y-axis, while leaving the second y-axis disabled, they will scale differently.

In that scenario I would expect the second axis to mirror the first one.

In this example the left axis is scaled from 0 to 100. I would expect the second axis to mirror the first one, or to be absent.
![grafik](https://cloud.githubusercontent.com/assets/14967448/22335162/d98e785c-e3dd-11e6-8232-b1aad0e99aa0.png)

Axis settings:
![grafik](https://cloud.githubusercontent.com/assets/14967448/22335227/26252eae-e3de-11e6-86de-9ec8888c3132.png)

Live update is enabled.

Habpanel version: 2.0.0

**Comment by ghys** [comment]
Thanks - should be fixed.
