### ISSUE TITLE
Multiple info in a single widget

### ISSUE THREAD

**Issue by TommySharpNZ** [openhab/org.openhab.ui.habpanel#14]
I'm sure this type of thing is on your roadmap already :-)
Being able to show multiple items details within a single widget would be very useful.
For example I'm more interested in TEMP than HUMID so a single widget with a large indication of temperature and a small indication of humidity would be perfect.
For someone else the importance might be the other way around so probably needs to be configurable where possible.
##

**Comment by mdilger** [comment]
I would find this useful as well.

**Comment by ghys** [comment]
Can be done with a template - reusable custom widget are also on the way.
