### ISSUE TITLE
chart X axis shows the name of the month (Feb)

### ISSUE THREAD

**Issue by jenskastensson** [openhab/org.openhab.ui.habpanel#140]
Since midnight Jan 31-Feb1 it seems the chart X axis shows the name of the month (Feb) instead of time. Is this a bug or expected?
 ![axisfeb](https://cloud.githubusercontent.com/assets/6616001/22500864/971c897c-e866-11e6-97e1-7188c0550a4f.gif)
http://demo.openhab.org:8080/habpanel/index.html#/view/weather-astro

**Comment by jenskastensson** [comment]
Update:  Feb. 2  displays as usual on time axis
![feb](https://cloud.githubusercontent.com/assets/6616001/22548297/1f048d96-e946-11e6-95fa-5502d03bf8a2.gif)

**Comment by ghys** [comment]
Yes, the first day of the month is displayed as the month abbreviated name (this was intended, but I wrongfully only had the charts over a >1M period in mind), and ends up screwing up the charts over shorter periods. Will fix, thanks for reporting!
