### ISSUE TITLE
Select current panel configuration from url

### ISSUE THREAD

**Issue by jenskastensson** [openhab/org.openhab.ui.habpanel#141]
Is it possible (or would it make sense) to be able to select current panel configuration from the url?
If it is not implemented, what would be the best way ?
![panelconfig](https://cloud.githubusercontent.com/assets/6616001/22501107/9666cfc8-e867-11e6-8df9-d05c53b252c6.gif)

**Comment by ghys** [comment]
I saw your use case on the forum, the need to be be able to control the current configuration externally was not a planned feature (and isn't possible at the moment), and TBH I'm not sure if that's such a good idea :)

**Comment by jenskastensson** [comment]
ok, thx for the reply.
