### ISSUE TITLE
Visual feedback for click or tap

### ISSUE THREAD

**Issue by AlleexxR** [openhab/org.openhab.ui.habpanel#142]
It would be nice, to get some visual feedback, when you click or tap an action widget. Is it possible, to add a CSS Pseudo class :active to the widget, with a different color or opacity? I tried with the switch widget in chrome developer tools and it worked as expected.

**Comment by kubawolanin** [comment]
Can you propose a solution via PR? Please read [contribution guidelines](https://github.com/openhab/org.openhab.ui.habpanel/blob/master/CONTRIBUTING.md) and after setting your environment and testing it, you're free to submit a solution by yourself! ;-)

**Comment by AlleexxR** [comment]
I never did a PR. It's just an additional CSS Property for Elements. I did it with the switch widget, just adding 
`.switch:active{background-color:rgba(255, 255, 255, 0.1)}` in web/app/widgets/switch/switch.scss

**Comment by ghys** [comment]
This makes sense, I'll have this in mind next time I update the styling (have a few things planned in this area as well, like the pointer cursor for dummy widgets etc.). Thanks for the idea.
