### ISSUE TITLE
State updates for widgets not working in Chrome HTTP

### ISSUE THREAD

**Issue by tommyherman** [openhab/org.openhab.ui.habpanel#145]
Hi!

When using a newer version of Chrome (i'm using v 56) on windows to display habpanel, widgets and switches are not updatng.
When displaying the same habpanel trough OpenHAB Cloud it updates fine.
It seems that Chrome only allows Service Workers on HTTPS conncections.

When browsing locally on my LAN the Chrome debug console says:
Service worker not registered (not using HTTPS?): SecurityError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

And when browsing trough OpenHAB Cloud it says:
Service worker registered

I could not find any previous issue of this problem, so I hope this has not been previously discussed.
And I cannot find any simple solution to this issue.

Any ways, I love HABPanel and am learning to take advantage of it's full potential, thanks for a great UI!

Regards,
Tommy Herman

**Comment by ghys** [comment]
@tommyherman the service worker is not related to your issue.
Can you follow the instructions here https://community.openhab.org/t/should-habpanel-refresh/14387/28?u=ysc and report back whether you can see the events arriving in the EventStream tab of the "events" request or not.
Thanks!

**Comment by tommyherman** [comment]
@ghys Sorry for not responding earlier, i was out of town and could not do any testing.
In the link you sent i found people talking about Sophos AV, as i use Sophos i tried to do a webpage exeption to the HABPanel site and state updates started working.

So for me all is hunky dory :)

Thank you for your help!

//Tommy
