### ISSUE TITLE
HABPanel Problem with MAP Binding

### ISSUE THREAD

**Issue by micropet** [openhab/org.openhab.ui.habpanel#146]
I use HABPanel to display only one temperature:
Number D25_Temp_aussen "Outside temperature [%. 1f ° C]"

That works great. If I now install the MAP binding I get the following error message:

Connection lost. Trying to reconnect.

If I remove the MAP binding, the display works again.

**Comment by ghys** [comment]
I'm guessing there is a problem with your mappings.
If you go to the developer tools (F12) while it's not working there should be errors in red in the Console & Network tab with more info on what's wrong.

**Comment by micropet** [comment]
Thank you. 
I have some mappings removed. Now I only use the zodiac, season and moon mapping. 

Now, the error no longer occurs.

**Comment by fugazzy** [comment]
I need to comment on this because I now ran into the same problem.
I have no clue what is meant by "developer tools (F12)"
Please help to find a direction into where to look for an error.
