### ISSUE TITLE
Rrd4j charts for group items cannot be displayed

### ISSUE THREAD

**Issue by dominicdesu** [openhab/org.openhab.ui.habpanel#15]
Hi,

habpanel currently only supports rrd4j charts for single items.
If a group item is selected, an empty chart is displayed.

Reason is the URL in [chart.tpl.html](https://github.com/openhab/org.openhab.ui.habpanel/blob/4468c54cef62d94d66186971b2d78ee008ba6841/web/app/widgets/chart/chart.tpl.html#L6), which should start with `/rrdchart.png?group=` instead of `/rrdchart.png?items=` in case the item is actually of type group.

**Comment by ghys** [comment]
Right, I'll have a fix, or you might have do a PR in the meantime ;)
