### ISSUE TITLE
Colorpicker does not list color groups

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/org.openhab.ui.habpanel#152]
The colorpicker in HabPanel only lists color items, but no color groups. As a workarround I've set the color group directly in the json text and it works very good. Can you extend the filter on the colorpicker to include color groups?

**Comment by ghys** [comment]
Ok, what's a "color group" though? A regular group?

**Comment by TheNetStriker** [comment]
Yes, I mean a regular group that contains only color items. Is there a way that such groups could also be included in the Filter?

**Comment by ghys** [comment]
With a few changes, yes. Thanks for bringing this to my attention :)
