### ISSUE TITLE
JS Module Error - 'undefined' is not an object

### ISSUE THREAD

**Issue by toneus** [openhab/org.openhab.ui.habpanel#153]
Safari & Chrome both return Connection Lost! message on iPad running JavaScript 1.7 iOS 5.1.1, but HABPanel loads fine on iPad running JavaScript 1.7 and iOS 9.3.5.

OpenHAB is 2.1.0 dated 2/1/17.

When navigating to HABPanel UI, I simply get the Connection Lost! message. I understand this is the general catch that JavaScript is in a Connecting status. I enabled the Safari debug console and indeed see there is an JS error under the covers.

JavaScript: Error
undefined
Error: [$injector:modulerr] http://errors.anjularjs.org/1.5.11/$injector/modulerr?p0=ng&p1='undefined'%20is%20not%20an%20object

From my research, it appears that there is possibly a 'ng' module inclusion issue here.

This could be a version issue with my ancient iPad, but I would really like to use it as a always on dashboard so if there is is a fix that would be awesome.

**Comment by ghys** [comment]
Hard to say without a stack trace or at least a file/line number.
Perhaps follow the advice here: http://stackoverflow.com/questions/10197895/ipad-javascript-error-not-helpful
So clone the repository and add a `window.onerror` handler in a `<script>` tag in index.html, and try to print the 4 parameters - it might give you a file/line of the error. If it's in HABPanel code, then we might come up with a solution. If it's in a library (vendor.js), it'll be more difficult...

**Comment by toneus** [comment]
I've Forked, Cloned, and Imported to my Eclipse instance. The Project is complaining about a missing required library:'patch'. I pulled the Master branch. Any assistance would be greatly appreciated.

Also suggestions on where to put the onerror? Will this work?

    <script>
        window.addEventListener('load', function() {
            if (navigator.serviceWorker) {
                navigator.serviceWorker.register('service-worker.js', { scope: './' })
                .then(function(r) {
                    console.log('Service worker registered');
                })
                .catch(function(what) {
                    console.info('Service worker not registered (not using HTTPS?): ' + what);
                });
            }
        });
        
        window.onerror = function (desc,page,line,chr)
        { alert('Line:'+line); }
    </script>

**Comment by ghys** [comment]
You can simply clone the repository in your `conf/html` folder on your openHAB instance then go to http://youropenhab:8080/static/org.openhab.ui.habpanel/web/ 
It's much simpler and no need to recompile the .jar.

I think it'll work to put the handler there, yes.

**Comment by toneus** [comment]
Thanks ghys, I took the approach of putting the web folder content into the html folder and used the static approach. Unfortunately, I think there will be a lack of detail. The onError dialog indicated Line: 0.

I'm happy to tweak the testing. Do any of the developers have an iPad 1 iOS 5.1.1 that can test?

**Comment by ghys** [comment]
@toneus can you try pasting this code in the index.html `<script>` tag:

```js
if (!Function.prototype.bind) {
  Function.prototype.bind = function(oThis) {
    if (typeof this !== 'function') {
      // closest thing possible to the ECMAScript 5
      // internal IsCallable function
      throw new TypeError('Function.prototype.bind - what is trying to be bound is not callable');
    }

    var aArgs   = Array.prototype.slice.call(arguments, 1),
        fToBind = this,
        fNOP    = function() {},
        fBound  = function() {
          return fToBind.apply(this instanceof fNOP
                 ? this
                 : oThis,
                 aArgs.concat(Array.prototype.slice.call(arguments)));
        };

    if (this.prototype) {
      // Function.prototype doesn't have a prototype property
      fNOP.prototype = this.prototype; 
    }
    fBound.prototype = new fNOP();

    return fBound;
  };
}
```
(from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill)

Wild guess but the absence of `Function.prototype.bind` is apparently a common issue.

**Comment by toneus** [comment]
@ghys - Sorry I was gone for so long, kinda gave up on the issue.

I think you've confirmed it. HABPanel now loads, and I'm able to source my server side configuration!

**Comment by ghys** [comment]
Finally added it - closed.
