### ISSUE TITLE
Switch State not updating at Habpanel UI

### ISSUE THREAD

**Issue by amarpulli544** [openhab/org.openhab.ui.habpanel#160]
Hello,

Switch state cannot update at Habpanel UI. I trying to update switch state through SNAVXbee2 binding download [here](https://github.com/g1velo/SNAVXbee2) and then binding export to jar file.  
 And here one more jar file required for communication between two xbee devices ,it's download [here ](https://www.versioneye.com/java/org.openhab.core:org.openhab.io.transport.serial/2.0.0.b2).
  Both jar files placed into addons folder in openhab2. I am using Xbee devices to update switch states in Habpanel UI. 
Once I will changed switch state from OFF to ON  (here communication between two xbee devices, one is Coordinator another one is End device) ,it's updating fine. But when i  changed switch state from ON to OFF from End deice by using XCTU Software. it's not updating at Habpanel UI.

Thanks,
Amar.

**Comment by ghys** [comment]
Hi,
Please verify the following:

* In Chrome, hit F12 and go to the Network tab;

* Verify you have a "events" entry like so (it shouldn't be red):

![](https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/b/bd3bfa61f9fe554b301bd3b97065ea22bd6827d7.png)

* Click on it and go to the EventStream tab:

![image](https://cloud.githubusercontent.com/assets/2004147/23832643/3e462028-0739-11e7-91ca-e13dd0c09125.png)

* Switch your item on and off and check if there are messages arriving - you should see new messages with `{"topic": "smarthome/items/<your_item>/state", ...`

**Comment by amarpulli544** [comment]
@ghys 

Yes I saw it should be like this  

`{"topic":"smarthome/items/DemoSwitch/command","payload":"{\"type\":\"OnOffType\",\"value\":\"OFF\"}","type":"ItemCommandEvent"}	
`

But here not updating the Switch State at User Interface side.
I mean Switch Icon not updating from ON to OFF state.
Please let me know the how to resolve this?

Thanks,
Amar

**Comment by ghys** [comment]
You should get events with `state` or `statechanged`, and types `ItemStateEvent` or `ItemStateChangedEvent`, those are events sent by the openHAB server when an item's state is updated. HABPanel cannot update the UI without them.
If you don't see these events there is a problem elsewhere, maybe with your binding.
Do you see other items updating?

**Comment by amarpulli544** [comment]
@ghys 

I get events only while sending commands to devices from openhab server. But when i was sending commands from device to openhab server not getting events.

Thanks,
Amar

**Comment by ghys** [comment]
Sounds like a device-specific issue then, not with HABPanel. Sorry I can't help you further 😕 
I'd suggest describing your configuration and your problem on https://community.openhab.org, surely there are people with the same hardware who might be able to help!

Thanks!
