### ISSUE TITLE
Add HABPanel Widgets from a Bundle

### ISSUE THREAD

**Issue by pkriens** [openhab/org.openhab.ui.habpanel#164]
I would like to add some widgets for a HABPanel into a bundle. I've not been able to find a way to do this. Did I miss it or does it not exist?

**Comment by ghys** [comment]
Sorry, it isn't supported at the moment. Custom widgets are tied to "panel configurations", there may be several of those to choose from, so adding widgets globally would require some changes/additions to the central persistence object.
It's an interesting idea though. I'll leave the issue open to track a potential new feature.

**Comment by pkriens** [comment]
If you could indicate  how (and in which sources this is handled) I could take a stab.

**Comment by 6Meghana** [comment]
Is there any way out how to create widgets from bundle.

**Comment by kirantpatil** [comment]
@6Meghana,  How are you trying to add code? 
Could you please list down your steps ? 
Thanks.

**Comment by 6Meghana** [comment]
I am trying to create my own new widget to habpanel UI something similar to switch, button etc. So, as of now 
•	The bundle org.openhab.habpanel.ui is cloned and the steps in CONTRIBUTING.md is performed.
After that, I imported the bundle into eclipse IDE once the build was successful there were errors (Package 'org.openhab.ui.habpanel' does not exist in this plug-in MANIFEST.MF	
) in Export-package: org.openhab.ui.habpanel in MANIFEST.MF file. This is limiting me to create jar file as I want to use the bundle in my binding. But I am able to running through debug mode.
•	I added classes(codes)  for creating new widgets which is not reflected in the habpanel UI in debug mode.

**Comment by ghys** [comment]
@pkriens currently widgets are defined in the `panelsRegistry` configuration variable for the `org.openhab.habpanel` service, inside the JSON structure like this (in a `customwidgets` structure):

```json
panelsRegistry = {
    "mynewpanel": {
        "updatedTime": "2017-03-08T17:38:44.475Z",
        "dashboards": [
            ...
        ],
        "menucolumns": 2,
        "settings": { ... },
        "customwidgets": {
            "music-control": {
                "template": "<div>\n  <h3>Artist: {{itemValue(config.artist_item)}}</h3>\n  <h4>Track: {{itemValue(config.track_item)}}</h4>\n  <div class=\"btn-group\">\n    <label class=\"btn btn-lg btn-default\"\n           ng-click=\"sendCmd(config.action_item, 'REV')\"><i class=\"glyphicon glyphicon-step-backward\"></i></label>\n    <label class=\"btn btn-lg btn-primary\" ng-if=\"itemValue(config.status_item) != 'PLAY'\"\n           ng-click=\"sendCmd(config.action_item, 'PLAY')\"><i class=\"glyphicon glyphicon-play\"></i></label>\n    <label class=\"btn btn-lg btn-primary\" ng-if=\"itemValue(config.status_item) == 'PLAY'\"\n           ng-click=\"sendCmd(config.action_item, 'PAUSE')\"><i class=\"glyphicon glyphicon-pause\"></i></label>\n    <label class=\"btn btn-lg btn-default\"\n           ng-click=\"sendCmd(config.action_item, 'FWD')\"><i class=\"glyphicon glyphicon-step-forward\"></i></label>\n  </div>\n</div>",
                "name": "Music control",
                "author": "YS",
                "settings": [
                    {
                        "type": "item",
                        "id": "artist_item",
                        "label": "Artist item"
                    },
                    {
                        "type": "item",
                        "id": "track_item",
                        "label": "Track item"
                    },
                    {
                        "type": "item",
                        "id": "action_item",
                        "label": "Action item"
                    }
                ]
            },
            "otherwidget": { ... }
        }
    },
    "otherpanel": { ... }
}

```

What I would propose is to put widgets provided by bundles in separate configuration variables; one per widget could make sense, this way each bundle would only have to define those variables when installing and clear them when uninstalling. You can use the `org.osgi.service.cm.ConfigurationAdmin` class in the bundle's code I guess to do that; HABPanel's bundle could also provide a helper class for that, but then your bundle would have a dependency to HABPanel - if for instance a binding bundle uses this feature to provision widgets it is not desirable).

By convention the configuration variables would be called `widget.<your_widget_id>`:
```json

panelsRegistry = ...
lockEditing = ...
initialPanelConfig = ...
widget.mybundlewidget = {

    same structure as above

    "name": "My bundle's widget",
    "author": "...",
    ....
}
widget.myotherbundlewidget = {
    ...
}
```

Then you would have to modify `app/services/openhab.service.js` to detect & read those additional configuration properties and store them in angular's `$rootScope`, persist them to the local storage in `app/services/persistence.service.js`, and modify a bunch of things to make them available in the designer (`app/dashboard/dashboard.edit.controller.js` & `app/dashboard/dashbord.edit.tpl.html`) and the template widget (`template.widget.js` in `app/widgets/template`). Ideally the list of custom widgets would be modified too (`settings/settings.widgets.list.html`) to display read-only tiles for "globally provisioned" custom widgets (those wouldn't be modifiable in the UI).

So it's not trivial, hope it makes sense though :)

**Comment by ghys** [comment]
Ended up implementing my proposal above in #171.
I'll post a new thread explaining everything in the forum tomorrow (and will link to it here), but an example project to distribute widgets via an OSGi bundle is already available here: https://github.com/ghys/habpanel-example-widget
Closing.
