### ISSUE TITLE
HabPanel UI not updating while made changes inside a habpanel bundle

### ISSUE THREAD

**Issue by amarpulli544** [openhab/org.openhab.ui.habpanel#165]
Hello @ghys ,

I would like to implement color picker widget  for  habpanel user interface like (Basic UI or Classic UI). 
As of now the habpanel provides HSL sliders and acKolor types.  Here I should made some changes along with acKolor files in habpanel bundle, but  it won't update at habpanel UI. Just i want remove save button and remove button in acKolor type of widget. Please let me know how i can remove those buttons.

Thanks,
Amar

**Comment by ghys** [comment]
You'll have to modify aCKolor (my fork actually) for this.
So you would fork https://github.com/ghys/aCKolor, make your changes, *bump the version number* (important) to e.g. `3.0.3-habpanel` (in its `bower.json`), rebuild it (don't remember how but it should be `npm install` then `gulp`). Then you change HABPanel's dependencies in `web/bower.json` to point to your version, and rebuild with `gulp` (in the `web` folder).

**Comment by 6Meghana** [comment]
@ghys can you please simplify the steps.

I made changes/modified the code and changed the version in aCKolor( https://github.com/ghys/aCKolor) ,how am I supposed to rebuild and where.

**Comment by ghys** [comment]
You build aCKolor by using `gulp` (look at its `gulpfile.js`, if I'm not mistaken it's re-generating `bower.json` from `package.json`).
Then you commit the results and push to your fork's repository, i.e. https://github.com/6Meghana/aCKolor

To build HABPanel itself please refer to [CONTRIBUTING.md](https://github.com/openhab/org.openhab.ui.habpanel/blob/master/CONTRIBUTING.md) - but before running `bower install`, change HABPanel's `bower.json` to update the aCKolor dependency to `https://github.com/6Meghana/aCKolor.git#3.0.3-habpanel`

**Comment by 6Meghana** [comment]
@ghys 
we followed the procedure mentioned by you, thank you , still the changes are not getting updated. so, can you please tell us where exactly the changes to be done is it in src or in dest folder.
We are trying to alter the color picker by removing the save and close button , we want the color picker to work similar to the color pickers as in Basic UI / Classic UI. Can you please let us know how can we resolve it.

**Comment by ghys** [comment]
The `dist` folder in aCKolor is where the minified versions of the JS & CSS files go after running `gulp`.
You should edit the `src` folder then run `gulp`.
If you're stuck building aCKolor you should ask its author directly at https://github.com/ckelsey/aCKolor/issues

**Comment by amarpulli544** [comment]
@ghys ,

I did as you said for editing aCKolor repository but won't updating at Habpanel UI.
My steps are 
1. Forking aCKolor repository from https://github.com/ghys/aCKolor.
2. Then clone forking repository from https://github.com/amarpulli544/aCKolor.git.
3. After cloning , through project directory then call ` npm install gulp` through command prompt.
4. Once it is done we modified and push to my repository( https://github.com/amarpulli544/aCKolor.git).
5. After that we build the Habpanel UI, by refering to  CONTRIBUTING.md file.
6. Before bower install we changed habbpanel bower.json file ( web/bower.json)
habpanel bower.json file after changed dependency

```
{
  "name": "habpanel",
  "version": "1.0.0",
  "homepage": "https://github.com/ghys/habpanel",
  "authors": [
    "Yannick Schaus",
    "Kuba Wolanin"
  ],
  "description": "Dashboard user interface for openHAB",
  "main": "",
  "moduleType": [],
  "keywords": [
    "dashboard",
    "panel",
    "openhab",
    "smarthome",
    "ui"
  ],
  "license": "EPL",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "~1.5.11",
    "angular-gridster": "~0.13.14",
    "angular-bootstrap": "^1.x",
    "angular-fullscreen": "~1.0.1",
    "angular-prompt": "~1.2",
    "angular-local-storage": "~0.4.0",
    "angular-route": "~1.5.11",
    "angular-sanitize": "~1.5.11",
    "angular-touch": "~1.5.11",
    "angularjs-slider": "~5.4.3",
    "d3": "^3.5.x",
    "ng-knob": "https://github.com/ghys/ng-knob.git#0.1.6",
    "sprintf": "~1.0.3",
    "inobounce": "iNoBounce#~0.1.2",
    "angular-ui-codemirror": "~0.3.0",
    "oclazyload": "ocLazyLoad#~1.0.9",
    "angular-clipboard": "~1.5.0",
    "bootstrap-sass": "^3.3.7",
    "roboto-fontface": "^0.5.0",
    "angular-ui-clock": "latest",
    "angular-file-saver": "~1.1.2",
    "event-source-polyfill": "latest",
    "angular-snap": "^1.8.5",
    "angular-ui-select": "^0.19.6",
    "selectize": "~0.12.4",
    "d3-timeline": "master",
    "aCKolor": "https://github.com/amarpulli544/aCKolor.git#3.0.3-habpanel"
  },
  "resolutions": {
    "angular": "~1.5.9",
    "d3-timeline": "master"
  }
}
```
7. After bower install and gulp build successfully. The Habpanel UI is not updated with changes made in aCKolor repository. Would you please us resolve it.

Thanks,
Amar.

**Comment by ghys** [comment]
Your repository looks good, so I don't know what's wrong.
Try running `bower list` in the HABPanel web directory to verify you have your `3.0.3-habpanel` version.
