### ISSUE TITLE
No way to sync between two devices?

### ISSUE THREAD

**Issue by deadcyclo** [openhab/org.openhab.ui.habpanel#167]
I have a raspberry with a touchscreen that I would like to sync from the server, but it simply doesn't work. Once I push the dashboard from a computer, I can get the same dashboard in the browser on the pi (chromium), but there simply is no way to get it to sync any updates I make on the other machine, bar emptying the localstorage on the pi and starting from scratch. 

Is this not an intended use case? Or have I completely missed something? Or is something not working?

**Comment by ghys** [comment]
If you use a (server-based) panel configuration on the second device (checking the radio button on the Advanced settings page), a page refresh should pick up the changes made on the first, more generally changes on either device will be saved on the server except when the version already there is newer.

There's a "last sync on..." indication displayed in the panel configuration list to check whether they are correctly saved or not.

**Comment by deadcyclo** [comment]
Hmm. Yeah. That's exactly how I expected it to work. The second one never picks up any changes, and the "last sync" timestamp never changes from the first sync timestamp. I'll try to get the pi hooked up to a bigger screen and investigate what is going on use network too over easer and see if I can track down the issue.
