### ISSUE TITLE
Color picker: Handle NULL states

### ISSUE THREAD

**Issue by Fohdeesha** [openhab/org.openhab.ui.habpanel#169]
My Color Picker controlling some RGB lights stopped working out of nowhere, I'm guessing it may be due to the adding of the alternative color picker style. Didn't change anything in my config.

Now clicking any of the HSL Sliders, they jump right back down to black. Checking openhab.log explains why - every time I try to use the sliders now I get this in the log - 

`2017-04-11 05:00:59.841 [WARN ] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/fWIFI_RGB_2' with an invalid status value '129,NaN,NaN'.`

I thought it might be cache or the dashboard, so I deleted my dashboard, created a new one, all on a new pc, and still getting the same problem. No matter what I do with the slider, at least one of the 3 values it returns is NaN. Using the habpanel bundled with openhab2 installed from debian repos, snapshot branch/repo

Also tried just selecting the new colorpicker mode, "aCKolor", and it results in a blank widget - http://i.imgur.com/wiL8wHL.png

**Comment by Fohdeesha** [comment]
so I grabbed the files directly from this repo, and added them as a static html site in openhab2. Then accessing that instance, the color picker works.

Then I go back to the bundled habpanel interface, and the picker is now working again. And suddenly the other Ackolor picker works too. Not Sure what's going on?

**Comment by ghys** [comment]
Very strange indeed.
I personally tried color pickers with the Hue binding. If you use something else maybe it doesn't report valid HSL values from time to time?
Try going to `http://<your_openhab_ip>:8080/rest/items/fWIFI_RGB_2` when you encounter the problem, to check the item's state has the expected format - 3 comma-separated integers e.g. `198,100,100`. If it isn't the case the widget is likely to break.

**Comment by Fohdeesha** [comment]
Looks like you're onto something. After a fresh openhab 2 start, the state is null? It's just sending the HSL/RGB values to an arduino via mqtt, is there special care I should use when defining a color item in openhab to make sure it has some "default state" other than null?

`{
  "link": "http://openhab2.home.lan:8080/rest/items/fWIFI_RGB_2",
  "state": "NULL",
  "type": "Color",
  "name": "fWIFI_RGB_2",
  "label": "RGB",
  "category": "slider",
  "tags": [],
  "groupNames": [
    "WIFI_RGB_2G"
  ]
}`

my item for it is just
`Color fWIFI_RGB_2 "RGB" <slider> (WIFI_RGB_2G)

If you define a new generic color item, does it also start out as null for you on a fresh start of OH2?
`

**Comment by ghys** [comment]
I never encountered NULL values for color items, but I can understand they might be occuring and the widget should handle them properly!

**Comment by ghys** [comment]
Should be fixed by #175 - reopen if necessary, cheers!
