### ISSUE TITLE
Color picker: null values still no-go

### ISSUE THREAD

**Issue by Fohdeesha** [openhab/org.openhab.ui.habpanel#177]
(sorry, wouldn't let me reopen the existing issue as I wasn't the one that closed it)

With the new update, the color picker still doesn't let you choose values if the item state is null.

An easy way to test is just add the following to your items file, you will see that when openhab starts up it sets the values to null unless there is a binding externally writing it's value

`Color Color_Test "Color Testing"`

(I use a rule to convert this item to rgb values which are then sent out via mqtt, hence no direct binding. I guess if you don't assign a binding to an item, this is when openhab makes its value NULL at startup)

**Comment by ghys** [comment]
Are you sure? Pretty sure I fixed it 😕 
Do you really have the most recent version? You can confirm that in the Karaf console:
```
openhab> bundle:list org.openhab.ui.habpanel
```
Should have the timestamp of the build in the Version column.

**Comment by ghys** [comment]
Ah, the last snapshot was built before the fix was merged:
https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/org.openhab.ui$org.openhab.ui.habpanel/lastSuccessfulBuild/

Make sure you get the newest version when the build timestamp in the above URL changes, probably later today.

**Comment by Fohdeesha** [comment]
That gives me:

`187 | Active |  80 | 2.1.0.201704251551 | HABPanel User Interface`

Edit: just saw your second reply. That's do it :P oops! Thanks for putting your time into this, I'm sure I'm one of maybe 2 people total it effects. 

I'm also experiencing a second issue, when I use the knob widget, and I set a range for the ring indicator thing, whenever the value of that item goes above that range the widget gets stuck and never updates again, not even the text in the center. It's driving me slightly crazy as I'm trying to use the knob as a read only display for my house watts, I'd like to have the range from 0-5000 watts as that's where the value lies 99% of the time but every once in a while it goes over to something nuts like 15kw when the AC starts and renders the widget useless until I f5 the page. Should I file an issue for that? If I can somehow get around that, habpanel will be perfect in my book. Using it on a large touchscreen controlling a plc, I can't tell you how much nicer it is to work with than the old HMI software

**Comment by ghys** [comment]
There's now a new build available on Cloudbees (*org.openhab.ui.habpanel-2.1.0-20170426.143721-40.jar*). Please try with this one and feel free to close the issue if it's resolved.

As for your other problem, you should open a separate issue with proper repro steps and the contents of the Javascript console (F12) when it happens. The widget probably crashes at some point.

Since you're running a recent build, you might also to beta test the new gauge widget:
https://github.com/ghys/habpanel-gauge-widget/releases/latest

**Comment by Fohdeesha** [comment]
working great now! thanks again. Will look into filing for other issue. Will check out the new widget!
