### ISSUE TITLE
Kiosk mode should set padding-top to 15px instead of 0

### ISSUE THREAD

**Issue by jimduchek** [openhab/org.openhab.ui.habpanel#178]
When ?kiosk=on is added, the header bar is removed and padding-top is set to 0px -- however, padding-left and padding-right are still set to 15px, creating an unsightly effect of different sized screen margins on the top/bottom as opposed to the left/right. It appears the 15px left/right margin is more or less hardcoded and not themed, so kiosk mode should match that.

Perhaps the padding-left/right should be set to 0px instead, while in kiosk mode, but that looks a little more complicated, and probably not the author's intent, but either way, I believe the padding should match.

**Comment by ghys** [comment]
You're right - done.
