### ISSUE TITLE
New selection list widget

### ISSUE THREAD

**Issue by dominicdesu** [openhab/org.openhab.ui.habpanel#18]
Hi,

would be nice to have a widget with a similar functionality like a button, but with a list of command values, which can be selected in a selection list (or similar).
My use case would be a list of playlists for my audio system. I don't want to make 10 buttons in order to support 10 different playlists :-) (or is there already a similar functionality which I missed?)

I know that recently possibility to create custom widgets was introduced. However, I think this could be a "basic" widget as there are probably many more use cases.
##

**Comment by ghys** [comment]
Agreed - openHAB 2 exposes the list of possible values for certain items and I wanted to do something with them, but I don't know how I want it to look like yet.

**Comment by kubawolanin** [comment]
Any plans to proceed with this?
I was thinking about it but since HABPanel is built around [Items](http://docs.openhab.org/concepts/items.html) and not [Sitemap Elements](http://docs.openhab.org/configuration/sitemaps.html), I see no real way to handle e.g. [`Setpoint`](http://docs.openhab.org/configuration/sitemaps.html#element-type-setpoint)s or [Switch mappings](http://docs.openhab.org/configuration/sitemaps.html#element-type-switch)

**Comment by ghys** [comment]
Exactly. The list of options could be set per widget, maybe with an accordion like the chart of the timeline.
Still undecided about the presentation, too. Could be a full screen modal menu like Basic UI, a Bootstrap dropdown...

**Comment by kubawolanin** [comment]
For the record - there's a custom widget made by @marcelrv doing what's requested by @dominicdesu:
https://community.openhab.org/t/selection-option-for-habpanel/14953/5

I guess we can close this issue as there's a solution in place.

**Comment by dominicdesu** [comment]
While the widget looks indeed nice, I don't think it scales for many entries. I was thinking of a list which is only visible during selection, not showing the items all the time.
However, as it is now possible to create custom widgets, I don't mind if this ticket is closed if it is not intended to add a selection list widget to the standard widgets.

**Comment by ghys** [comment]
I'll leave it opened as I haven't completely given up on this, even though there are quite a few alternatives ;)
The widget could also have an option to display as a modal menu, a group of buttons, a dropdown...
PRs are welcome!
