### ISSUE TITLE
Image widget sourcing from Image item

### ISSUE THREAD

**Issue by andreasreinhardt** [openhab/org.openhab.ui.habpanel#182]
Currently, the image widget only supports a fixed URL or a String item containing the URL, but OpenHAB2 also supports the Image item which contains the image in raw format.
It would be great, if this could also be supported.
Unfortunately, I cannot provide a pull request for it by myself as my JavaScript knowledge is very limited.

**Comment by ghys** [comment]
It shouldn't be too hard especially since Paper UI supports them already. Eager to test them properly with the Kodi binding channels for thumbnail and fanart though ;)

**Comment by ghys** [comment]
I think that'll do it!

**Comment by waras2017** [comment]
Hi  ghys,
is it possible to replace to code snippet from #182 in an existing openhab 2.2 installation?
Or is it possible to export the Image Widget from an openhab 2.2 installation, fix the code and import it as an custom widget?
