### ISSUE TITLE
Integration guide for development

### ISSUE THREAD

**Issue by thhart** [openhab/org.openhab.ui.habpanel#183]
Hi, I am developing a little plugin for openhab and checked out the development tree 2.1.0 with eclipse. Unfortunately habpanel is not included in this. Is it possible to have a small instruction how to integrate from a dev point of view?

**Comment by ghys** [comment]
Hi, you have several options;

- If you only need to run HABPanel, not develop it, you can simply add the .jar to your target platform: follow the instructions in https://community.openhab.org/t/how-to-run-habmin-in-the-eclipse-ide/7246 (it's for HABmin but it's a similar situation for HABPanel).
You can download the .jar of the latest HABPanel build here: https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/org.openhab.ui$org.openhab.ui.habpanel/

- fork and clone this repository, then import the project into your Eclipse workspace (File > Import > Existing Projects into Workspace > Select root directory, check the project and click Finish).

In both cases edit the Run or Debug configuration in Eclipse (*openHAB_Runtime*) and make sure the plug-in is checked, either from the Workspace or the Target platform category.

![image](https://user-images.githubusercontent.com/2004147/26983436-199e2e52-4d3c-11e7-8297-250632a291f9.png)
