### ISSUE TITLE
Right part of screen covered with black bar - Android & Chrome

### ISSUE THREAD

**Issue by ppieczul** [openhab/org.openhab.ui.habpanel#188]
OpenHAB build: 2.1.0~20170616220700-1
Device: Samsung Galaxy Tab Pro SM-T525 LTE
OS: Android 4.4.2
Chrome: 58.0.3029.83

Right part of the screen is always covered with a black vertical bar, more or less the size of the menu that is shown when swiping screen right.

Does not occur if switching chrome to desktop mode. Only in tablet mode.
Also does not occur on iPad, iPhone, MacOS, only the configuration described above.

Screenshot attached.
![screenshot_2017-06-17-22-33-04](https://user-images.githubusercontent.com/10254718/27256190-394950c4-53ae-11e7-9461-44f349b831b6.png)

**Comment by ghys** [comment]
Seems hard to debug without your exact configuration I fear 😕 
Tried on 2 different Android tablets (4.4.4 and 7.0.1) with latest Chrome and I'm not able to reproduce this.
Could be an issue with snap.js, the library used to build the menu. Maybe try http://jakiestfu.github.io/Snap.js/demo/apps/default.html, is there a similar problem there?

**Comment by ppieczul** [comment]
In the meantime the issue appeared on other Web pages too. And habpanel started showing fine too. Looks like some sporadic issue with this tablet configuration. Definitely not specific to habpanel. Thanks for your help.
