### ISSUE TITLE
Chart tooltip doesn't render correctly with Material theme

### ISSUE THREAD

**Issue by mhilbush** [openhab/org.openhab.ui.habpanel#189]
The text in the n3-line-chart tooltip is the same color as the background color when using the Material theme.  Below is a screen snip showing the issue.

<img width="538" alt="screen shot 2017-06-18 at 8 07 06 am" src="https://user-images.githubusercontent.com/19286354/27260560-68d0b55e-53fd-11e7-9a63-5d56ab2449eb.png">

Edit: I see the same behavior occurring in the Timeline widget.

**Comment by ghys** [comment]
Thanks. This will be fixed with #187.
