### ISSUE TITLE
Let image widget display ImageItem and URLs of StringItem

### ISSUE THREAD

**Issue by dominicdesu** [openhab/org.openhab.ui.habpanel#19]
Currently the image widget only supports a fixed URL.
Actually, OH2 has an ImageItem, which contains an image in raw format. Would be nice if I could select such an item and display it.

Additionally it would be great if I could select a String item, and read the URL from the item, instead of hard-coding it in the widget.

Sorry for creating all these tickets... 😃 if I find some time to get familiar with angular I'll also try to contribute.
##

**Comment by digiltd** [comment]
You could always set the url to an image that you replace however you wish. i.e. have a image file in 'conf/icons/classic' called something like `image-for-habpanel.jpg`. Then as long as you keep the filename the same you can replace it using whatever method you wanted.

**Comment by ghys** [comment]
Closed in #143.

**Comment by sagig76** [comment]
I also need this functionality for the image widget.
It works with iFrame, the problem is that the image size I get is too large and the iframe can't resize the image. how can we get the same functionality in the image widget?
