### ISSUE TITLE
Timeline widget should refresh automatically

### ISSUE THREAD

**Issue by gersilex** [openhab/org.openhab.ui.habpanel#191]
Hi there,

I think the timeline widget lacks an option to automatically refresh (much like the image widget). 
The refresh interval should optionally be automatically calculated by the combination of the selected time range and the width of the widget (and therefore effective horizontal resolution).

Here is the most terrible mockup you have ever seen:

![image](https://user-images.githubusercontent.com/2018039/27837594-73b5962a-60e5-11e7-89a2-6a54c02c9a35.png)

**Comment by servim** [comment]
Hello! This is a very necessary opportunity!

**Comment by ghys** [comment]
This is now implemented and activated by default - there is no setting.
FYI, the refresh interval is set to the displayed period / 120 (arbitrary value).
i.e.

- for an 1h period => every 30s
- 4h => every 2min
- 1 day => every 12min

and so on.
