### ISSUE TITLE
Habpanel 404s on events

### ISSUE THREAD

**Issue by BClark09** [openhab/org.openhab.ui.habpanel#196]
SSE work on sitemaps by subscribing to an eventsource in `/rest/sitemaps/events` and receiving updates through it:

![image](https://user-images.githubusercontent.com/8983584/27990082-5e821380-6443-11e7-97b1-9f7585c413d3.png)

However, every now and then, HABPanel receives a 404 error, it doesn't look like there's any subscription and tries to connect to `/rest/events` directly. This spams the console with errors:

![image](https://user-images.githubusercontent.com/8983584/27990068-27c79e6e-6443-11e7-9482-0a96c1de0f28.png)

I can't figure out what causes this to happen, but it will only ever happen to habpanel!

**Comment by ghys** [comment]
I have seen this before: https://community.openhab.org/t/should-habpanel-refresh/14387

But I don't have an explanation why `/rest/events` gives you a 404, it definitely should work...

![image](https://user-images.githubusercontent.com/2004147/27994752-e0110d7c-64c3-11e7-951b-793653108987.png)

Maybe something to do with your items config (transformation services are often the culprit)

> I can't figure out what causes this to happen, but it will only ever happen to habpanel!

Paper UI calls this endpoint too, so I'll assume it's broken as well?

**Comment by BClark09** [comment]
I don't get any eventsource items come up in the network configuration for PaperUI, even when it's working on HABPanel. I find I can keeping restarting it until I no longer get a 404 though.

The only transformation service I have is "map", I have uninstalled it and will let you know if I come up against the problem again.

**Comment by ghys** [comment]
@BClark09 did you finally get it working properly?

(Yes, I'm doing some house-cleaning with my issues 😁)

**Comment by BClark09** [comment]
Thanks @ghys. I got it once more but it seems like all was well after a restart. Couldn't find anything in the debugging so will close this up and reopen if it becomes an issue again! ☺️
