### ISSUE TITLE
No connection to*.items file, if it starts with a comment

### ISSUE THREAD

**Issue by iNNOCENCE1337** [openhab/org.openhab.ui.habpanel#198]
Not a very common error, I think - but maybe it´s worth to fix.

If the *.items file begin with a comment `//` , habpanel shows the "Connection lost" message and can´t reach the openHAB-items.

**Comment by ghys** [comment]
Thanks, good to know, but it isn't a HABPanel problem per se.
Any misconfiguration which breaks the `/rest/items` API will lead to this behavior.
You probably have more information in your server logs or by calling `/rest/items` directly (probably responding a HTTP 500 error with an exception message).
