### ISSUE TITLE
Wishlist: Clickable Icons or Buttons with a Backgroundimage

### ISSUE THREAD

**Issue by HubertusH** [openhab/org.openhab.ui.habpanel#2]
I have some scenes for my rollershutters (night, sun etc.) with corresponding images:
![image](https://cloud.githubusercontent.com/assets/16612146/17401672/24fecbf2-5a4f-11e6-9a6b-9561366511f4.png)
It where very nice when the images are klickable (or have a linked OH Item) or the buttons can have a image.
##

**Comment by ghys** [comment]
I'm working on proper icon support for widgets, it should be done in a few days or this weekend.
