### ISSUE TITLE
development environment 

### ISSUE THREAD

**Issue by aryeharmon** [openhab/org.openhab.ui.habpanel#200]
How would i make a development environment for modifying only html and JavaScript.
each change i would have to recompile the java bundle for testing?

**Comment by ghys** [comment]
Simply clone this repository in your `conf/html` directory (`/etc/openhab2/html` if you use a package install) and point your browser to:
http://openhab_host:8080/static/org.openhab.ui.habpanel/web/index.html
When you're done you can then recompile the Java bundle.

**Comment by aryeharmon** [comment]
@ghys thanks
