### ISSUE TITLE
knob option displayInput incorrectly parsed

### ISSUE THREAD

**Issue by VibroAxe** [openhab/org.openhab.ui.habpanel#211]
When loading a widget-knob from within a custom template we are unable to access the displayInput value properly due to it's boolean nature. If we wish to set options.displayInput to false, the controller evaluates the second half of the if forcing the value to true. I believe this should probably do some forms of a null check instead

 ```
               displayInput: (vm.widget.displayInput) ? vm.widget.displayInput : true,
```

https://github.com/openhab/org.openhab.ui.habpanel/blob/master/web/app/widgets/knob/knob.widget.js#L84

Alas, i'm not an angular dev so i'm not sure the correct edits or I would submit a pull request with a fix. Would be good to get this fixed though as it makes for more options with custom templates.

**Comment by ghys** [comment]
Of course you're right. :)
Thanks!

**Comment by VibroAxe** [comment]
👍 Your welcome, keep up the good work habpanel is fantastic
