### ISSUE TITLE
more than one oh instance

### ISSUE THREAD

**Issue by LarsES8266** [openhab/org.openhab.ui.habpanel#212]
id like to make itemvalues from more than one oh intance visible, is it possible to provide a full rest url of an item from somewhere else ?

**Comment by ghys** [comment]
Not possible. And receiving updates would imply subscribing to events from the other instance, monitoring the other connection etc.
If you want to make external API calls it is is possible with an external Angular controller or directive you put in your static folder and load with `oc-lazy-load`, see exmaples linked in the "Advanced: Injecting custom JavaScript code" chapter of https://community.openhab.org/t/habpanel-development-advanced-features-start-here/30755.

A better idea is to link your OH instances, for example with MQTT, so items from the second one can be controlled from the first, see https://community.openhab.org/t/multiple-instances-of-openhab/7284
