### ISSUE TITLE
[Selection] Incorrect label after making selection

### ISSUE THREAD

**Issue by FredericMa** [openhab/org.openhab.ui.habpanel#219]
Hi,

I've created a selection widget with a list of commaseparated choices like this:
`PowerOff=Alles uit,TV=TV, Plex=Plex,Chromecast=Chromecast,Wii=Wii`

When I open HABpanel, all is visualized correctly:
![image](https://user-images.githubusercontent.com/7840263/30422881-83e93576-9941-11e7-92a6-2d6126c815fe.png)

When I make another selection the label doesn't seem to be used. For example, if I select "Alles uit" again, PowerOff is visualised:
![image](https://user-images.githubusercontent.com/7840263/30422952-ad170be4-9941-11e7-91e9-212a7188e845.png)

It is not related to the space in between "Alles uit" since I also tested it without the space.

This is my configuration of the widget:
![image](https://user-images.githubusercontent.com/7840263/30423025-e9308f06-9941-11e7-8536-db7a1f9d463b.png)

Thanks!

Greetings,
Frederic

**Comment by ghys** [comment]
I think the idea was to combine the "cmd=label" syntax for choices with the MAP transformation for the actual current state display, but your expectation was reasonable as well and made more sense - fixed.
Thanks!

**Comment by FredericMa** [comment]
Looking forward to have it fixed in my setup!
Thanks a lot for the quick reply.
