### ISSUE TITLE
Build dashboard with link widgets

### ISSUE THREAD

**Issue by s-simma** [openhab/org.openhab.ui.habpanel#22]
Is it possible to build the dashboard page with widgets (lets say "link widgets"). If these "link widgets" could also be used inside the pages itself it would give a height flexibility to move between pages.
This would also solve the problem using HABpanel on a mobile phone, where it is only possible to have 4, max. 5 dashboards (on iPhone - all the other are not visable)
##

**Comment by neohusky** [comment]
YES! I would love this feature also. Dashboard linking for habpanel. Dream come true.

**Comment by mdilger** [comment]
I would also like this.  I was thinking today that it would great to have a another level of panels that could be accessed from a link on a panel. My use case would be to have friendly (WAF) summary & group control widgets on the first level then more detailed individual widgets on the second level.

**Comment by ghys** [comment]
I've been planning this for quite some time, I'll add it to the button widget - instead of only being able to send a command to an item, it will support several types of actions, including navigating to another dashboard.

Btw, I just pushed #23 which adds some layout and display options to the main menu (this was long overdue).

**Comment by ghys** [comment]
Example:
![image](https://cloud.githubusercontent.com/assets/2004147/18731562/eda84154-805c-11e6-8273-3a2757023cb4.png)

**Comment by neohusky** [comment]
It's turning into a fantastic piece of software. This welcome addition certainly increases the WAF!  

Thank you for your continued work on this.

**Comment by kaikreuzer** [comment]
I fully agree with @neohusky, really fantastic progress!

**Comment by mdilger** [comment]
Awesome, thank you for the great work!

**Comment by s-simma** [comment]
@ghys 
It's like christmas !!

**Comment by s-simma** [comment]
@ghys 
For mobile devices it would be great, if the "font-size" for the dashboard title could be configured ("Dashboard Card Settings")
Is this possible ?

**Comment by ghys** [comment]
Thanks very much for the praise! :)
I experimented with the background URL option and some pictures hotlinked from Wikipedia and quickly got interesting results... if you're fed with the blue theme and SVG backdrops and want something prettier ;)
![image](https://cloud.githubusercontent.com/assets/2004147/18739611/1f145f8c-80a5-11e6-86f6-4c3a5acceefa.png)

@s-simma yes there will be other settings for the tiles, I missed this one.

**Comment by neohusky** [comment]
@ghys Praise is given when its deserved.   I just quickly tested your above work in progress and it does look good. I can't wait to try the enhancements to the button widget to link to dashboards.

I was just looking at the image above and thinking ahead: It would be great to be able to disable the gear icon, date and fullscreen button and make the dashboard take up this extra space.  Your providing enough widgets that date info can be displayed on a main dashboard(template widget) and maybe the config gear and fullscreen icon can be called up via a button on a settings dashboard.

**Comment by ghys** [comment]
I kinda like it... But I guess it can be made optional.

**Comment by isigmund** [comment]
I would also like to see a possibility to hide the header and I agree it should be something that can be enabled or disabled. Maybe an URL Parameter would be good to conrol if the header line is displayed or not

**Comment by isigmund** [comment]
There is the possibility to navigate to a different dashboard by using the template widget:
![image](https://cloud.githubusercontent.com/assets/5901482/19903912/b20aad10-a070-11e6-9977-c8908aebbfd8.png)

Here is he coding that I used for the 2 navigation buttons.
Left:
```
  <button class="btn btn-lg" 
          style="background: red; color: white" 
          ng-click="sendCmd('strCurrentPanel', 'Livingroom')">
    <i class="glyphicon glyphicon-chevron-left"></i>
  </button>
```

Right:
```
  <button class="btn btn-lg" 
          style="background: red; color: white" 
          ng-click="sendCmd('strCurrentPanel', 'Outdoor')">
    <i class="glyphicon glyphicon-chevron-right"></i>
  </button>
``` 

You need a string item (strCurrentPanel in my case) that is used to to trigger the navigation. You will have to add that item in the advanced settings like so:
![image](https://cloud.githubusercontent.com/assets/5901482/19904042/4f0bf484-a071-11e6-96fa-26b1ad61da17.png)

The drawback of this approach is that if you add dashboards you have to adjust the coding and for each dashboard the coding has to be different to navigate to the next or previous dashboard.

**Comment by ghys** [comment]
> I would also like to see a possibility to hide the header and I agree it should be something that can be enabled or disabled. Maybe an URL Parameter would be good to conrol if the header line is displayed or not

Not related to this issue, but this was a good idea. Implemented in #58.

**Comment by kubawolanin** [comment]
Hello!
Take a look on my custom widget that does pretty much same thing @s-simma requested.
[Custom widget: Dashboard Link](https://community.openhab.org/t/custom-widget-dashboard-link/17560)

It's based on HABPanels redirection capability.

Cheers

**Comment by ghys** [comment]
Now a built-in feature of the button widget! see #92.
