### ISSUE TITLE
Restructure docs folder

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/org.openhab.ui.habpanel#222]
Hello!
I've finally worked on https://github.com/openhab/openhab-docs/pull/372 - All changes on my side are practically finished, it would be great if you could add some changes here. I didn't created a PR because I didn't want to f'up your blame history 😊 

All these changes will basically make the adoption in the docs repo easier and we do not have to take tedious special steps over there, which might create problems in future. Please let me know if you have an issue with any of them. 

1. Please name the `doc` folder `docs`
2. Please name the index article `habpanel.md`
3. Please move all images to a folder called `docs/images`
4. Please add a common start to all image file names, e.g. `habpanel_screenshot0.png` or `hp_screenshot0.png`
5. Please add the following to the top of `habpanel.md`

```text
---
layout: documentation
title: HABPanel
---

{% include base.html %}

<!-- Attention authors: If you want to improve or enhance this article, please go to: -->
<!--   * https://github.com/openhab/org.openhab.ui.habpanel/issues -->
<!--   * https://github.com/openhab/org.openhab.ui.habpanel/blob/master/docs/habpanel.md -->
```

Best! Thomas

**Comment by ghys** [comment]
Hi Thomas! Sweet to see now on this front!
Your requests are reasonable; I'll address them this week - and bring the doc up-to-date while I'm at it.

**Comment by ThomDietrich** [comment]
@ghys I'm sorry to bother you but it seems like number one of my list was a bit too ambitious. Most other openHAB addons have a doc folder and while I believe "docs" is generally more common, would you please revert that one change? Thanks!

**Comment by ghys** [comment]
@ThomDietrich no worries - and I was around so here goes: #236 😉

**Comment by ThomDietrich** [comment]
Thanks! I'll have to do the matching change over in docs and then we'll hopefully end up with long awaited result :) I'll keep you posted!

**Comment by ThomDietrich** [comment]
I'm afraid you've missed the links in the README.md

**Comment by ghys** [comment]
Ack! Completely forgot about those. Done, thanks!

Btw: in habpanel.md I included links to other parts of the docs like this:

    [demo setup package]({{base}}/configuration/packages.html#demo-package-sample-setup)

They obviously don't work in GitHub but am I safe to assume they'll work on docs.openhab.org?

**Comment by ThomDietrich** [comment]
Looks good to me.

The only problem I fear is, that files and headlines might change at some point and the link suddenly doesn't work any longer. At some point I'll have to add a link checker to the deployment toolchain...
