### ISSUE TITLE
Frames (with for example grafana graphs) are "flickering"

### ISSUE THREAD

**Issue by SR-G** [openhab/org.openhab.ui.habpanel#223]
Hello.
I don't know where the problem is, but i'm facing the following issue.
When HABPanel doesn't contain any frames, everything is fine (correctly updated, without any visual glitches).
But as soon as i add a frame (in order to display a graph built through grafana), i have some kind of "flickering" (not related to the refresh timeout !)
@see : https://www.screencast.com/t/SUuTyD2e (refresh 120 secs, but screens "flickers" constantly).

Maybe related to https://github.com/openhab/org.openhab.ui.habpanel/issues/192 ?

edit : running OpenHAB 2.2.0-SNAPSHOT build #1044

**Comment by ghys** [comment]
Looks weird indeed, I don't seem to have this problem (with another page - are you sure the Grafana page doesn't have its own refresh mechanism?).
You can look in the Network tab in the developer tools, the initial page refreshes initiated by HABPanel will have "vendor.js:95" in the Initiator column. If you don't see anything like that (apart from every 120 seconds), the refreshes and the flickering aren't caused by HABPanel.

**Comment by SR-G** [comment]
At first glance, i wasn't thinking the problem may be grafana related : indeed, when i open the embedded url in a new tab, the page and the graph are never refreshed automatically. 

I've just checked the network tab : in my situation, everything is constantly reloaded (you can see in the screencast that the page itself reloads, as seen with the "reload" button). In the network tab i see "vendor.js", openab?from=...&to=...", "grafana-icons.ttf", font.min.css, and so on.

**Comment by ghys** [comment]
Can you post a screenshot of your Network tab with the filter applied to "Doc" as highlighted in red:

![image](https://user-images.githubusercontent.com/2004147/30871481-53666018-a2e7-11e7-91a0-60e6032b6f6b.png)

In this example the widget is set to reload Paper UI every 10 seconds and is working as expected - the requests are all initiated from vendor.js. Does the list clears itself every time there is a refresh (meaning the entire page is reloaded)?

**Comment by SR-G** [comment]
Hey. Sure. Here it is : https://i.imgur.com/UCpT912.png
Widget still set to reload every 120 secs. 
The list is not cleared, but i'm still surprised to see the "reload" button activated (in the chrome toolbar).

**Comment by ghys** [comment]
> i'm still surprised to see the "reload" button activated (in the chrome toolbar).

I have it too and that's probably to be expected.

The URLs are wrong because the `?_t=` querystring appended by HABPanel to bypass caching should be `&_t=...` in this case. Maybe that's the issue. I'll try to have a fix in the next few days.

**Comment by ghys** [comment]
This should fix the above - hopefully it will address your issue too.
If not please let me know.

**Comment by openhab-5iver** [comment]
I think I may be experiencing this, or something similar (OH 2.2.0 snapshot build 1067, HABPanel 2.2.0.201710181101). Everything looks normal until I set a refresh interval for a frame widget. 
![image](https://user-images.githubusercontent.com/21967853/32044907-dfd883e6-ba0c-11e7-9b6e-23aa1f9f93af.png)

This also occurs if just the widget is added, without a URL but a refresh interval configured. Oddly this will also display a mini HABPanel that can be navigated... at least until it refreshes.
![image](https://user-images.githubusercontent.com/21967853/32045791-2c7c5356-ba0f-11e7-8e5a-9a87574b4cb3.png)

![image](https://user-images.githubusercontent.com/21967853/32045911-81d90858-ba0f-11e7-957e-a4c486de4702.png)

**Comment by ghys** [comment]
Try again with the next snapshot ([build #170 or later](https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/org.openhab.ui$org.openhab.ui.habpanel/)).

**Comment by openhab-5iver** [comment]
I just updated to build 171 and this change appears to have corrected the issue. Thank you!

**Comment by Xento** [comment]
I'm using version  2.2.0.201711260007 and images still flicker when cachebusting is enabled.
When I disable ist, the image doesn't get updated.
Before it worked and it only seems that cachebusting was the default behavior before.
I think you have to load the new image in the background and when its finished loading replace the old one.
