### ISSUE TITLE
[Feature Request]Hide Dashboards from side Drawer

### ISSUE THREAD

**Issue by Confectrician** [openhab/org.openhab.ui.habpanel#238]
I have already thought about this and it seems i am not alone, so here's the issue.

**It would be useful to be able to hide Dashboards from the side Drawer, if not needed there.**
---
### My usecase
I am currently using several "Status" Dashboards which provide my mostly technical information that isn't interesting for anyone else than me.
But my wife and every Guest has the same long Dashboard list which may be confusing for someone.

For me it would be perfect to have some "invisible" Dashboards, which i then would make accessible through Buttons in a single "Status-Dashboard" for me.

### Other usecases
I have seen two other usecases where people asked for a feature like this:
https://community.openhab.org/t/new-display-options-incl-experimental-custom-widgets-everywhere/34140/8?u=confectrician
and
https://community.openhab.org/t/examples-of-habpanel-solutions/15557/254?u=confectrician

---
I don't know if these are edge cases, but we won't know if we don't talk about it here. 😄 
So let's discuss.

**Comment by ghys** [comment]
An option to hide them from the side drawer seems fair, as long as they're still visible at least in the main menu.
