### ISSUE TITLE
Can't save knob settings when using decimal values for color ranges

### ISSUE THREAD

**Issue by kstruessmann** [openhab/org.openhab.ui.habpanel#240]
When I try to edit the HabPanel I can't change settings in the Knob Widget and when I press save nothing happens. The console says "An invalid form control with name='name' is not focusable."

**Comment by ghys** [comment]
Cannot reproduce.
Browser/OS/HABPanel versions? Happens every time? Does it work again when starting from scratch in an incognito browser window?

**Comment by kstruessmann** [comment]
Hi, 

it happens everytime since yesterday and doesn't make any difference neither if I try it in Chrome or Firefox nor Windows or MacOS. When I'm restarting from scratch I can reproduce this error. 

Here is my test config from scratch: 
`[
    {
        "id": "foo",
        "name": "foo",
        "widgets": [
            {
                "name": "New Widgetsd",
                "sizeX": 4,
                "sizeY": 4,
                "item": null,
                "type": "knob",
                "row": 0,
                "col": 0,
                "floor": 0,
                "ceil": 100,
                "step": 1,
                "ranges": [
                    {
                        "min": 5,
                        "max": 16.5,
                        "barColor": "#3399FF",
                        "$$hashKey": "object:1614"
                    },
                    {
                        "min": 17,
                        "max": 31,
                        "barColor": "#FF9933",
                        "$$hashKey": "object:1615"
                    }
                ],
                "$$hashKey": "object:26"
            }
        ],
        "row": 0,
        "col": 0,
        "$$hashKey": "object:21"
    }
]
`

**Comment by ghys** [comment]
Ok now I have it too with your config.
The problem is, the 16.5 max value in the first range leads to that error because the field only accept integer numbers. If you change it to e.g. 17 it works again.
You can see it while trying to save while the field is visible:

![image](https://user-images.githubusercontent.com/2004147/32142745-c0805ac6-bc9d-11e7-8b72-5c0cbb538857.png)

Anyways, decimal values should be accepted, I'll have a fix.
Thanks!

**Comment by kstruessmann** [comment]
You are my hero! Thank you for your quick response and have a nice weekend.
