### ISSUE TITLE
implement itemTags(item.name)

### ISSUE THREAD

**Issue by gersilex** [openhab/org.openhab.ui.habpanel#242]
As *User* I want to have a method similar to `itemValue(item.name)` that returns the list of tags(Strings) an item has to use it in custom templates.

openHAB REST API Example:
```json
{
  "link": "http://openhab:8080/rest/items/notification_washing_machine_finished",
  "state": "ON",
  "type": "Switch",
  "name": "notification_washing_machine_finished",
  "label": "Washing machine finished",
  "tags": [
    "notification-success, anotherTag"
  ],
  "groupNames": [
    "notifications"
  ]
}
```

Maybe the name itself does not really fit, feel free to change it. I'm also open to other ideas to implement this. I just felt like I could really use the existence of tags to control how something looks or behaves in HABPanel.

**Comment by ghys** [comment]
You can use `getItem(itemname).tags` for that I believe, or you tried that
already and it didn't work?

`itemsWithTag(tagname)` is there as well if you need it.

**Comment by gersilex** [comment]
You are absolutely right. `item.tags` returns the list of tags. Thanks!
