### ISSUE TITLE
Touch directives for habpanel templates

### ISSUE THREAD

**Issue by VibroAxe** [openhab/org.openhab.ui.habpanel#243]
The existing user templates are fantastic, but there are some significant implementation barriers when using a touchscreen device (as most tablets are), particularly if you wish to use angular mousedown/mouseup events rather than onclick.

It would be really helpful (and I believe simple?) to add the nglar/ngTouch module from https://www.npmjs.com/package/ngtouch into the user template scope. The existing angular/ngTouch module only provides access to the ng-swipe-[left/right] and not the underlying touchstart/end events which truly enable customization.

Would this be something you would consider I think it would be very helpful?

**Comment by ghys** [comment]
@VibroAxe sure, I have no objections provided there's no side effects with existing behaviour.

In the meantime, you can try downloading it to your html folder (from https://raw.githubusercontent.com/nglar/ngTouch/master/build/ngTouch.min.js) and lazy-loading it in your template like so:
```html
<div oc-lazy-load="'/static/ngTouch.min.js'">
  <div class="btn btn-default btn-lg"
       ng-touchstart="sendCmd('test', 'ON')"
       ng-touchend="sendCmd('test', 'OFF')">touch me</div>
</div>
```
(Disclaimer: I can't test right now so can't promise it works...)

See https://oclazyload.readme.io/docs/oclazyload-directive and https://community.openhab.org/t/habpanel-development-advanced-features-start-here/30755 chapter _Advanced: Injecting custom JavaScript code_ for more :)

**Comment by VibroAxe** [comment]
Interesting.. 

I hadn't come across the lazy load bits, i'll go do some testing and see how it responds.

Will report back later!

**Comment by VibroAxe** [comment]
ngTouch is working perfectly with lazy-load , thanks @ghys. I'm not seeing any issues / conflicts with anything currently.

I'd argue this is still a useful thing to add into the templating toolbox, but nowhere near as important now I know about lazy-load. I'll leave it up to you if it's worth leaving the issue to add, or just closing it with the lazyload solution

**Comment by ghys** [comment]
Yes, it's not a big overhead by any measure, HABPanel is primarily for touch devices anyway and it could prove useful from time to time, so I don't see why not.
I'm keeping this open and will add it next time I get around to messing with dependencies again.

**Comment by ghys** [comment]
All things considered, I'm going to close this issue, because:
- this library defines the same 'ngTouch' module as the standard Angular library (https://docs.angularjs.org/api/ngTouch) which is already included, so it creates a conflict;
- it doesn't seem to be really maintained.

If you would like to use it, please use the lazy-loading technique as described above.

Thanks.
