### ISSUE TITLE
Sliders sometimes won't appear in modals

### ISSUE THREAD

**Issue by kusanghi** [openhab/org.openhab.ui.habpanel#244]
Have a problem, I used to turn up for a slider widget:

When pressing on button first, slider Widgets do not appear
Then close the pop up and open the back, slider widgets appear.
Here is my html templates on habpanel :

```
<script type="text/ng-template" id="myModalContent.html">
    <div class="container" style="padding: 30px; border: 1px solid #456;">
      <a ng-click="$close()" class="pull-right btn btn-danger">X</a>
      <h3 style="color: white">All Lights</h3>
<div ng-init="TretKitchenDenTranLightLevel = {
                       	'item': 'TretKitchenDenTranLightLevel',
                        'floor': 0,
                        'ceil': 100,
                        'step': 0,
                        'precision': 1,
						'unit': '%',
                    		}">
</div>
<widget-slider ng-model="TretKitchenDenTranLightLevel">
    </div>
</script>
<button class="btn btn-default btn-lg"
        ng-click="openModal('myModalContent.html', true, 'lg')">
  Open Modal
</button>
```
This is my description video : [https://drive.google.com/file/d/1gUMvG1eQoUnNRyZ74XlH3hHCY_IMAX5O/view?usp=sharing](https://drive.google.com/file/d/1gUMvG1eQoUnNRyZ74XlH3hHCY_IMAX5O/view?usp=sharing)
This issue when using the slider, other content works well.

**Comment by ghys** [comment]
It seems like race condtion - after displaying the popup an update event is broadcasted, making the slider appear, but on the first time the popup is invoked it's sent before the slider has finished loading, therefore it doesn't receive it. I tried a few things trying to fix it, without success for now. This is related to #214.

**Comment by kusanghi** [comment]
I have asked this issue from angular slider and instruction fixes : https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load
but I don’t know what to edit this code in openhab.

**Comment by ghys** [comment]
Yes, I tried that before but it caused other problems - the dimensions are not always right so the slider would appear.
It is actually done already when handling the update event I referred to above.

https://github.com/openhab/org.openhab.ui.habpanel/blob/master/web/app/dashboard/dashboard.view.controller.js#L32...L38
