### ISSUE TITLE
Image Widget changed behavior

### ISSUE THREAD

**Issue by s-simma** [openhab/org.openhab.ui.habpanel#246]
Static image URL: http://192.168.1.14:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=1234562 (Foscam C1, Firefox)

**Refresh interval: 2 seconds**

The old picture is deleted before the new one is displayed (-> results in flashing image)
With Snapshot #996 the picture is stable (not flushing at all)
This only happens if refresh interval is used.

**Comment by ghys** [comment]
Related to the cache busting changes introduced by #239.
