### ISSUE TITLE
Ability to fetch sitemaps as dashboards dynamically

### ISSUE THREAD

**Issue by kubawolanin** [openhab/org.openhab.ui.habpanel#25]
It would be great to be able to [construct the sitemaps as in Project Rotini](https://github.com/igorgladkov/rotini/wiki/Button-Widget) and then have HABpanel recognize them as valid dashboards.

Obviously, that would require following strict semantics of the widget, like:

```
Frame label="TV {widget:button,icon:tv}" {
  Switch item=TV mappings=[
    ON="Turn on"
  ]
}
```

What do you think? 😄 
I've seen @kaikreuzer comment somewhere that openHAB is leaning towards flow without need of creating sitemaps (or maybe I'm wrong), so I don't know if it'd be applicable in the future.
##

**Comment by ghys** [comment]
Having HABPanel using "new-gen" sitemaps as dashboards has been discussed as the project was just starting, there's been an interesting discussion then.

The gap is frankly not that huge, though it would need (and I'm thinking out loud here):

1. HABPanel supporting multiple levels of dashboards: probably implemented as a widget being able to link to - and define - a "sub-dashboard"
2. a way in openHAB's sitemaps to define arbitrary key-values specific for the target UI at each level, for each widget in the sitemap (a little bit like vendor-specific CSS properties e.g. ```-webkit-whatever```) and with the ability of being posted back to the server - [link to ESH](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java)
3. a clever way to persist the sitemaps on disk, in the configuration, with their additional properties... maybe vanilla JSON?

[More discussion here](https://www.eclipse.org/forums/index.php/t/1072530/)

**Comment by kubawolanin** [comment]
Hey @ghys,

Ad. 1, Rotini resolves this issue [by introducing "pages" to the sitemaps](https://github.com/igorgladkov/rotini/wiki/Sitemaps#sitemap-with-pages). It simply takes Text widget as a group. Not sure if it's the best possible option, but it works! 😄 

Ad. 3. That'd be awesome! Vanilla JSON would be great. I imagine initial HABpanel instance with example dashboards ready for you to just point the right openHAB items - and you're ready to go.

Cheers,
K

**Comment by ghys** [comment]
#31 implements the ability to read openHAB's sitemaps.
It's not ready to be merged yet though.

**Comment by ghys** [comment]
This feature is abandoned as discussed in #31.
