### ISSUE TITLE
Allow custom icons in dummy widget

### ISSUE THREAD

**Issue by Loidt** [openhab/org.openhab.ui.habpanel#255]
The dummy widget currently allows choosing an icon shown on HABPanel in the widget settings. However if you prodived a custom icon in /etc/openhab2/icons/ than this icon can not be choosen from the list of available icons. 

A solution to this would be that the dummy widget shows the icon defined for the category of the corresponding item. In this case the widget settings only need to provide a switch that definies if the category icon should be shown or not. So that the user is still in control of displaying the icon.

**Comment by ghys** [comment]
This use case is covered by the "Custom icon" option available in all icon pickers, added in https://github.com/openhab/org.openhab.ui.habpanel/commit/3aeb256a0d4d1016c501dd5ed809222e6c872776. There is no way to get a list of the icons you added to the standard set, but if you know the name you can set it with this option.
See: https://community.openhab.org/t/icon-pickers-now-support-manual-entries/31508 for details.

**Comment by Loidt** [comment]
Nice, thats meets my use case.
