### ISSUE TITLE
Option to keep drawer open

### ISSUE THREAD

**Issue by monsdar** [openhab/org.openhab.ui.habpanel#257]
I would like to configure the Sidebar to stay open. It would ease navigation in that no swipe is needed and all Panels are visible all the time.

It could be done with a "Pin-symbol" in the top-right corner like Visual Studio does it:
![Pin-image](http://i.msdn.microsoft.com/dynimg/IC616896.png)

Alternatively this could be an item in the Advanced configuration screen.

**Comment by monsdar** [comment]
In the meantime: Is there an easy workaround, like editing the CSS or similar, to bring this fix in?

**Comment by ghys** [comment]
It's a good idea, and I had already 😄 ... however the snap.js library used to make the drawer doesn't support it natively 😞 

> Is there an easy workaround, like editing the CSS or similar, to bring this fix in?

This seems to work:
```css
.container {
    left: 265px;
    width: calc(100% - 265px);
}
.header a[title="Menu"] {
    display: none;
}
```
However, the swipe gesture added by snap.js remains and it cannot be disabled easily without modifying the code.

I'll add an option. Ideally this would be (also optionally) "responsive" i.e. automatically activated when the width is like >768px.

**Comment by monsdar** [comment]
Sounds really good!
Where can I find the file to edit? I'm running OpenHabian

**Comment by ghys** [comment]
Create a `fixedheader.css` file in the `html` folder of your config (`etc/openhab2`) then reference it in the Additional stylesheet in the settings screen: `/static/fixedheader.css`

**Comment by monsdar** [comment]
Works like a charm!
