### ISSUE TITLE
Moving widgets between dashboards

### ISSUE THREAD

**Issue by kubawolanin** [openhab/org.openhab.ui.habpanel#26]
It would be a great addition to the Edit mode if we could quickly move widget to the pointed dashboard. 

There are two options to accomplish this, from the UX perspective:
- We could add a new tab in the Settings modal with `Dashboard` dropdown field and it would indicate where this widget is situated currently. Changing its value would result in moving it elsewhere.
- "Move" action would be accessible directly from the widget (like cog icon etc.) 

What do you guys think?

I'd add Enhancement label there if I could :)

**Comment by ghys** [comment]
This has already been filed as #10.
I was planning to put a "Clone to..." dropdown next to the Delete button in the settings. That way, you're still in the conext of your current dashboard, and you can clone the widget to the same dashboard. Also the position/size needs to be reset or it would possibly overlap other widgets in the target dashboard.

If you want to move the widget, you just delete it after it's cloned.
