### ISSUE TITLE
Chart period set to "Y" shows empty chart

### ISSUE THREAD

**Issue by s-simma** [openhab/org.openhab.ui.habpanel#265]
If i set the period to "Y" (year ?) the n3-line-chart is empty.
All the other (M,4M etc. work fine)
Service provider : rrd4j

**Comment by ghys** [comment]
They work here.
You'll have to provide more details than that if you want some help 🙄
openHAB logs, Javascript console errors, etc.
Go to http://openhab:8080/rest/persistence/items/[your_item]?serviceId=rrd4j&starttime=2017-01-01T14%3A00%3A00Z and see if there's any data returned.

**Comment by s-simma** [comment]
Thank's for help,

in 2017 ther are no data points and the answer for
........serviceId=rrd4j&starttime=2017-01-01T14%3A00%3A00Z
{"name":"TempAussen","datapoints":"0","data":[]}
if it takes data from 1 year span this seems ok for me.

But if i change the start point to 2017-01-09:
........serviceId=rrd4j&starttime=2017-01-09T14%3A00%3A00Z
{"name":"TempAussen","datapoints":"10","data":[{"time":1515110400000,"state":"9.7013888888889123762737654033116996288299560546875"},{"time":1515153600000,"state":"8.1321126760563657853708718903362751007080078125"},{"time":1515196800000,"state":"7.46120448179275541633614921011030673980712890625"},{"time":1515240000000,"state":"3.450694444444428743423713967786170542240142822265625"},{"time":1515283200000,"state":"2.901388888888877470861871188390068709850311279296875"},{"time":1515326400000,"state":"1.2203626220362593368662373904953710734844207763671875"},{"time":1515369600000,"state":"2.313472222222208163344703280017711222171783447265625"},{"time":1515412800000,"state":"1.8319444444444432651408760648337192833423614501953125"},{"time":1515456000000,"state":"3.75712290502794932223196155973710119724273681640625"},{"time":1515499200000,"state":"2.35527777777777647116863590781576931476593017578125"}]}

for me the problem seems to be that the request is not set to "Actual date - 365" if Period "Y" is selected.

**Comment by ghys** [comment]
Right, I don't know why it works with me but it's about time I fixed that anyway.
Should be fixed in #266 - thanks!
