### ISSUE TITLE
Fetching current time in template widget

### ISSUE THREAD

**Issue by claell** [openhab/org.openhab.ui.habpanel#293]
I'd like to create a custom clock and date widget by using the template widget.

Is there a simple way to get the current time there?
I have seen approaches creating an item with the current time in OH and accessing it from the template widget. I was wondering whether there is an easier (direct) way to access the time from there.

**Comment by ghys** [comment]
Use the standard clock widget.
Example:
```html
<div ng-init="clockmodel={'mode': 'analog', 'digital_format': 'dd.MM.yyyy HH:mm:ss'}">
	<widget-clock ng-model="clockmodel"></widget-clock>
</div>
```

**Comment by claell** [comment]
Maybe I should have written, what I want to achieve:

First row displays the time (font size 50)
Second row displays the date (font size 25)

Currently I am using two clock widgets on top of each other, but I was looking for a way to achieve this with only one widget. Also later maybe changing to a different font or other styling things.

**Comment by claell** [comment]
@ghys Is this possible?

**Comment by ghys** [comment]
Sure why not?
In fact `widget-clock` is just a wrapper around `ds-widget-clock` so you might want to use that instead, it's easier.
```html
<div>
  <ds-widget-clock show-digital digital-format="'HH:mm:ss'" style="color: lightgray; font-size: 50pt; font-weight: bold;"></ds-widget-clock>
</div>
<div>
  <ds-widget-clock show-digital digital-format="'fullDate'" style="color: gray; font-size: 25pt;"></ds-widget-clock>
</div>
```

**Comment by claell** [comment]
Thanks for the code!
