### ISSUE TITLE
Knob widget should allow floating point numbers as min and max values

### ISSUE THREAD

**Issue by dominicdesu** [openhab/org.openhab.ui.habpanel#30]
The knob widget currently only supports whole numbers as min and max values.
I think it would make sense to support floating point numbers as well. My theromstat has a minimum value of 4.5, which I currently cannot set in the knob widget.
Note that the step supports floating point numbers, So I can go from 4 to 4.5 to 5 to 5.5 and so on. I just cannot set the start value as 4.5.

**Comment by ghys** [comment]
Did it for the slider too (same issue)
