### ISSUE TITLE
Feature request: Display options in Widgets

### ISSUE THREAD

**Issue by vzorglub** [openhab/org.openhab.ui.habpanel#300]
Could the option to display the name be optional in the Dummy widget and in the Timeline widget
Even if we set the name to nothing, the widget space is still taken. (I hope is makes sense)

**Comment by ghys** [comment]
Yes, it makes sense :)
Though I'm sure about the timeline widget, there needs to be some room at the top for the tooltip appearing when hovering a bar.

**Comment by vzorglub** [comment]
Maybe the tooltip could appear below the cursor when on the top line
