### ISSUE TITLE
[Feature Request] Add number format to the Knob widget

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/org.openhab.ui.habpanel#306]
I suppose this could be a bug, but the Knob widget does not display the item with any formatting, and formatting is not offered as an option. My preference would be to display this data without decimals...
![image](https://user-images.githubusercontent.com/21967853/41480254-ca96006c-709b-11e8-8a5b-c6617d9369b9.png)

Some discussion here... https://community.openhab.org/t/habpanel-knob-round-value/46345

**Comment by ghys** [comment]
Good catch, this was indeed missing. #307 adds it.
