### ISSUE TITLE
Change color of background or set image as background

### ISSUE THREAD

**Issue by Nic0205** [openhab/org.openhab.ui.habpanel#32]
The color of the background should be made choosable by user. At the moment the background is only in black. The page/dashboard color should be editable or even better there should be the possibility  to take a personal image as background.

Greetings Nic

**Comment by ghys** [comment]
Was feeling like adding some theming tonight :smile: 
You can't choose the background per se but this is better IMO.
Use the 'translucent' theme with a background image.
