### ISSUE TITLE
Update bootstrap

### ISSUE THREAD

**Issue by shutchinson** [openhab/org.openhab.ui.habpanel#322]
Hi all,

Great job on habpanel. I notice that it is using Bootstrap v3.3.7. Can we update this to v4.1.3?

I appreciate that this may break some themes but v3.x is no longer being developed.

https://github.com/openhab/org.openhab.ui.habpanel/blob/3e854c8a9ec52c1a4fe535ba65a7887fa9d2e572/web/bower.json#L47

**Comment by ghys** [comment]
Thanks for the suggestion, but as you rightfully pointed out there are a lot of community-produced stuff which rely on a stable set of frameworks. There are simply too many [breaking changes](https://getbootstrap.com/docs/4.1/migration/) from 3.x; a lot of classes are gone, as well as the Glyphicons, which makes it difficult to do a painless migration.
Additionally a number of dependencies - most notably https://angular-ui.github.io/bootstrap/ - are only compatible with Bootstrap 3.x.

I don't actually see the fact that Bootstrap 3 is no longer being developed as a problem, in fact that's true to some extent for the majority of the framework and libraries making up HABPanel now. Web development being as it is (new major versions of frameworks being often complete rewrites with no backwards compatibility), swtiching to a more modern, actively developed stack means that HABPanel would itself have to be rewritten from scratch too, which is not in the plans for now.
