### ISSUE TITLE
Wrong display of Cyrillic letters on item update

### ISSUE THREAD

**Issue by 8666** [openhab/org.openhab.ui.habpanel#323]
Cyrilic text is not properly displayed on item update

As you can see here

[https://imgur.com/DKHlQsE](https://imgur.com/DKHlQsE)

The text is ??? if it is changed while the current tab is active, pressing refresh or going to other dashboards and coming back fix the text

The text is from a map file

**Comment by 8666** [comment]
I had problems making the transform files work with Cyrillic on linux with OpenHab2, on windows and OH1 everything was easy. Now my map file looks like this

`[22:15:03] root@openhab2:/etc/openhab2/transform# cat vre.map
undefined=\u043d\u0435\u043f\u043e\u0437\u043d\u0430\u0442\u043e
uninitialized=\u043d\u0435\u043f\u043e\u0437\u043d\u0430\u0442\u043e
chanceflurries=\u043c\u043e\u0436\u043d\u043e\u0441\u0442 \u0437\u0430 \u0441\u043b\u0430\u0431 \u0441\u043d\u0435\u0433
chancerain=\u043c\u043e\u0436\u043d\u043e\u0441\u0442 \u0437\u0430 \u0434\u043e\u0436\u0434
chancesleet=\u043c\u043e\u0436\u043d\u043e\u0441\u0442 \u0437\u0430 \u0441\u043b\u0430\u0431 \u0434\u043e\u0436\u0434
chancesnow=\u043c\u043e\u0436\u043d\u043e\u0441\u0442 \u0437\u0430 \u0441\u043d\u0435\u0433
chancetstorms=\u043c\u043e\u0436\u043d\u043e\u0441\u0442 \u0437\u0430 \u0433\u0440\u043c\u043e\u0442\u0435\u0432\u0438\u0446\u0438
clear=\u0432\u0435\u0434\u0440\u043e
cloudy=\u043e\u0431\u043b\u0430\u0447\u043d\u043e
flurries=\u0441\u043b\u0430\u0431 \u0441\u043d\u0435\u0433
fog=\u043c\u0430\u0433\u043b\u0430
hazy=\u0441\u043c\u043e\u0433
mostlycloudy=\u043f\u0440\u0435\u0442\u0435\u0436\u043d\u043e \u043e\u0431\u043b\u0430\u0447\u043d\u043e
mostlysunny=\u043f\u0440\u0435\u0442\u0435\u0436\u043d\u043e \u0441\u043e\u043d\u0447\u0435\u0432\u043e
partlycloudy=\u0434\u0435\u043b\u0443\u043c\u043d\u043e \u043e\u0431\u043b\u0430\u0447\u043d\u043e
partlysunny=\u0434\u0435\u043b\u0443\u043c\u043d\u043e \u0441\u043e\u043d\u0447\u0435\u0432\u043e
rain=\u0434\u043e\u0436\u0434
sleet=\u0441\u043b\u0430\u0431 \u0434\u043e\u0436\u0434
snow=\u0441\u043d\u0435\u0433
sunny=\u0441\u043e\u043d\u0447\u0435\u0432\u043e
tstorms=\u0433\u0440\u043c\u043e\u0442\u0435\u0432\u0438\u0446\u0438

`

**Comment by 8666** [comment]
Update from console works properly... Any tips for having problem-free OpenHab2 on Linux with Cyrillic text?

**Comment by ghys** [comment]
Sorry, can't help much with that, since it doesn't seem to be specifically related to HABPanel but an issue with the map transformation, you might want to try asking on https://community.openhab.org? There are likely users using Cyrillic who might be able to help!

**Comment by 8666** [comment]
OK thanks you can close it.
