### ISSUE TITLE
Error 413 (Payload Too Large) - when saving >1999 lines of JSon to server

### ISSUE THREAD

**Issue by MDAR** [openhab/org.openhab.ui.habpanel#324]
Hi

I have tried to add a couple of widgets (Duplicates of one widget) to my design, but as soon as my JSon file is larger than 1999 lines, I see Error 413 (Payload Too Large)

Seen in a popup in PaperUI when attempting to "Lock editing" or paste the JSon file (While debugging)

I can confirm that if I allow my HabPanel JSon file to be any more than 1999 lines, I get the Error : 413 (Payload Too Large) error.

Which is a shame as I'd love to put in a great Thermostat Widget the @tomvancutsem has written.

FYI

It seems okay to have more than 2000 lines if the JSon file is saved and accessed locally, but attempting to store >1999 lines of JSon on the controller causes the 413 error.

[Community Post 46275](https://community.openhab.org/t/payload-too-large/46275/3)

**Comment by ghys** [comment]
As far as I understand, this is a problem with HABPanel but openHAB Cloud. So you should reopen your issue on https://github.com/openhab/openhab-cloud/issues, thanks!
