### ISSUE TITLE
widget "Button" (function request)

### ISSUE THREAD

**Issue by servim** [openhab/org.openhab.ui.habpanel#325]
Hi! I'm not sure what I'm writing in the right place, sorry :)
The button is a powerful widget, I like it very much, I use it to navigate between panels, displaying the value of some element on it. The only thing I really miss is the dynamic icon for the selected item.
Example: on the button icon - network. If the network element is turned on, the icon is blue, if off, gray. We see the gray icon, there is no network, click on the widget and switch to the panel - the network where the timeline widget will show the history of the network element.
Now I have to have 2 widgets, the dummy shows the state of the element, the button switches the panel, and I would like two in one!
PS I apologize for the bad (Google) English. Maybe I did not say well what I want, then ask me again. [Earlier I already tried to ask about it](https://github.com/openhab/org.openhab.ui.habpanel/issues/321).

**Comment by ghys** [comment]
Will be considered as a standard feature, but you also achieve this with a template widget or a custom widget with an HTML link to the other dashboard (`<a>`) and a properly `<widget-dummy>` inside).

Something like:
```html
<a href="#/view/otherdashboard" style="position: absolute; left: 0; top: 0; width: 100%; height: 100%;"
   ng-init='model={ "name": "Network", "item": "Network_Item_Name", "iconset": "freepik-gadgets", "icon": "wifi-router", "icon_size": 64 }'>

	<widget-dummy ng-model="model"></widget-dummy>

</a>
```

Check https://community.openhab.org/t/solved-where-to-start-with-habpanel/50940/2?u=ysc for essential topics on the community forum, or post in https://community.openhab.org/c/apps-services/habpanel if you need help.

**Comment by servim** [comment]
Thanks, that solved my problem. But anyway, I'll be glad to see this addition in the standard "Button" widget.
Offtopic: Formatting does not work in the "Button" widget.
