### ISSUE TITLE
HabPanel android app constantly asks for user/password combination when the app is restarted

### ISSUE THREAD

**Issue by dastrix80** [openhab/org.openhab.ui.habpanel#327]
Hi All,

This does not happen with OpenHab App. Only HabPanel.

I use HabPanel externally on HTTPS 443 via a local instance of openhab cloud.

everytime I restart the app, my credentials for OH2 Cloud must be entered into HabPanel.  Why can the app not just save these credentials?

Can anyone assist in working out why this happens? its highly annoying because if a person rings my door bell, by the time I punch in the credentials ive missed the call.

Thanks!
Kris

**Comment by ghys** [comment]
There is no such thing as an "HABPanel Android app", HABPanel is a web page, so the credential management is handled by your browser.

Or maybe you're referring to HABPanelViewer (https://community.openhab.org/t/habpanelviewer/34112), I don't remember if it can store credentials, but you can ask on the thread.

**Comment by dastrix80** [comment]
Yes,the HabPanel Viewer is what I'm discussing here.
