### ISSUE TITLE
Wrong state displayed when options are available

### ISSUE THREAD

**Issue by krabo0om** [openhab/org.openhab.ui.habpanel#335]
I have a Z-Wave thermostat, that as a few modes (off, heat, eco heat, full power..).
When I use a selection widget and as choices source *server-provided*, it will display an incorrect state in a special case, which makes this a rather rare bug (I guess).
The item as provided by the server:

```json
{
  "link": "http://server-ip/rest/items/Thermostat_ThermostatMode",
  "state": "1",
  "stateDescription": {
    "pattern": "%s",
    "readOnly": false,
    "options": [
      {
        "value": "0",
        "label": "Off"
      },
      {
        "value": "11",
        "label": "Economy Heat"
      },
      {
        "value": "1",
        "label": "Heat"
      },
      {
        "value": "15",
        "label": "Full Power"
      },
      {
        "value": "31",
        "label": "Manual"
      }
    ]
  },
  "editable": true,
  "type": "Number",
  "name": "Thermostat_ThermostatMode",
  "label": "Thermostat mode",
  "category": "Temperature",
  "tags": [],
  "groupNames": []
}
```
In this case I selected state 1, which - according to the state description - is "Heat". However, option number 1 (starting with 0, thus second item -> `options[state]`) is displayed, which is "Economy Heat".

Paper UI displays it correctly. It also works correct, just display wrong. But since those two are the most crucial settings, it is rather annoying. 

Can someone confirm this bug and my assumptions?

**Comment by ghys** [comment]
Thanks. A nasty bug indeed - #336 should fix it!
