### ISSUE TITLE
Fullscreen does not work anymore in Chrome

### ISSUE THREAD

**Issue by sidamos** [openhab/org.openhab.ui.habpanel#339]
Looks like Chrome changed something in the last version. When I click on the fullscreen option (arrow in the upper right), it does nothing and I get this exception in the browser console:
vendor.js:119 TypeError: Failed to execute 'webkitRequestFullscreen' on 'Element': parameter 1 ('options') is not an object.
    at Object.enable (vendor.js:447)
    at Object.all (vendor.js:435)
    at Object.toggleAll (vendor.js:469)
    at DashboardViewController.vm.goFullscreen (dashboard.view.controller.js:69)
    at vendor.js:255
    at b (vendor.js:127)
    at e (vendor.js:281)
    at b.$eval (vendor.js:147)
    at b.$apply (vendor.js:147)
    at HTMLAnchorElement.<anonymous> (vendor.js:281)

Happens in openHAB 2.3.0 and 2.4.0, Chrome on Linux and Android.

Still works OK in Firefox.

**Comment by ghys** [comment]
Thanks, (unfortunately) I can confirm this.

**Comment by olialb** [comment]
Same here, I switched to edge to watch my habpanel in full screen.
Any idea if this can be fixed?

**Comment by sidamos** [comment]
The fix is easy, but the author of Habpanel has to do it because I know no way of injecting global Javascript into Habpanel:
document.documentElement.requestFullscreen() works on the new Chrome versions.

I only have a workaround for Android: Use the Habpanelviewer app.
