### ISSUE TITLE
Widgets on main Dashboard

### ISSUE THREAD

**Issue by neohusky** [openhab/org.openhab.ui.habpanel#34]
Hi

I know its not planned but would you reconsider thinking about adding widgets on the main dashboard.

I'm not a developer so I wouldn't know your reasons behind it, but, could you not do away with the "main dashboard" and just have dashboards with the dashboard card as a widget.  Under your settings page, miscellaneous settings you could set a default "main" dashboard.
##

**Comment by ghys** [comment]
Not completely out of the question, maybe add some item-related data first, but it's not currently a priority.

**Comment by neohusky** [comment]
Thanks for your consideration @ghys
