### ISSUE TITLE
humidity svg problem

### ISSUE THREAD

**Issue by xelfer** [openhab/org.openhab.ui.habpanel#354]
I’m trying to configure habpanel to show humidity from a Xiaomi sensor. It currently has a broken humidity image: https://i.imgur.com/LS1gGH6.png 

The image error I’m getting is due to the URL being used to create the image, http://192.168.0.10:8080/icon/humidity?format=svg&state=61.87%20%

The addition of ' %' in the state is breaking it and giving a “org.eclipse.jetty.http.BadMessageException: 400: Unable to parse URI query” error. 

Is there any way to fix this in habpanel? Can I somehow just send the value without the ' %'? I’m not really sure how.

**Comment by LuckyMallari** [comment]
Can you post how your item is updated?

**Comment by xelfer** [comment]
It comes from the humidity reading here: https://i.imgur.com/ELEJOQa.png

**Comment by LuckyMallari** [comment]
The icon expects a number so you should use a proxy item to remove the percent sign. A url encoded string also worked:

http://192.168.0.10:8080/icon/humidity?format=svg&state=61.87%20%25

Not a HabPanel issue though

**Comment by xelfer** [comment]
Thank you, I wasn't aware of what may be causing it. I'll look into proxy items. Thank you!
