### ISSUE TITLE
Issues in compiling

### ISSUE THREAD

**Issue by arctus** [openhab/org.openhab.ui.habpanel#363]
Tried following the guide in Contribute.md in building the habpanel locally, however just can not go beside "mvn clean package" step. It always gives me the error with "missing dependency - com.google.gson", see image below.

![unnamed](https://user-images.githubusercontent.com/6660289/58083636-0b010980-7bc2-11e9-8120-0d2c440dcb1a.png)

Maybe my setup is invalid, thank you in advance for your suggestions.

**Comment by ghys** [comment]
Sorry this repository is not maintained anymore, HABPanel has been transferred to https://github.com/openhab/openhab-webui which uses a new build system.
