### ISSUE TITLE
Cannot install habpanel in b4

### ISSUE THREAD

**Issue by SuperOok** [openhab/org.openhab.ui.habpanel#39]
Following [this post](https://community.openhab.org/t/openhab-2-0-beta4-has-been-released/14110) I installed the snapshot release via apt-get and tried to install the habpanel from within the paperui.

However, I always get this exception:
`00:56:54.516 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-package-standard; type=karaf.feature; version="[2.0.0.b3,2.0.0.b3]"; filter:="(&(osgi.identity=openhab-package-standard)(type=karaf.feature)(version>=2.0.0.b3)(version<=2.0.0.b3))"
00:56:54.531 [INFO ] [smarthome.event.ExtensionEvent      ] - ui-habpanel: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-package-standard; type=karaf.feature; version="[2.0.0.b3,2.0.0.b3]"; filter:="(&(osgi.identity=openhab-package-standard)(type=karaf.feature)(version>=2.0.0.b3)(version<=2.0.0.b3))"
`
I guess in the beta 4 the version is 2.0.0.b4 so the dependency to b3 is too strict.

**Comment by mdilger** [comment]
Try updating the latest nightly build.  Not sure how you do that via apt-get.

Suggest you post the above issue on the openHAB Community as there will be others their who will be able to help.

**Comment by SuperOok** [comment]
Ok, I did a vanilla install or my Raspbian from scratch. Now it works. Must have been some messing up with older versions...
