### ISSUE TITLE
New analog clock widget

### ISSUE THREAD

**Issue by isigmund** [openhab/org.openhab.ui.habpanel#41]
I would like to add an analog clock widget to habpanel. I am planing to use http://deepu.js.org/angular-clock/ as the basis for this. 
It would look like this:
![image](https://cloud.githubusercontent.com/assets/5901482/19323887/267d4e26-90bf-11e6-9673-fd19495f5e31.png)

**Comment by ghys** [comment]
Nice! As said in the other issue: "try to avoid linking to the Syncopate font on Google's CDN, in fact try to avoid it at all and use the Roboto font".
Looks like it's the case :)

**Comment by isigmund** [comment]
no need for that font, I only need a small js file and a css as added dependency

**Comment by isigmund** [comment]
@ghys I have a quick question on how to handle the files that are added by gulp to the vendor folder. When I create the pull request, do you expect the added/changed (angular-clock.css, angular_clock.js and vendor.js) files in the vendor folder to be part of the PR or can I expect that bower and gulp get executed automatically in the main repository ?

**Comment by ghys** [comment]
You should add their minified versions to the gulpfile.js among the other dependencies, then run `gulp` before committing, so that they end up concatenated in the vendor.css and vendor.js files. If you have local modifications you can override styles in a scss file then run `gulp sass`.
The goal is: it should be working after cloning without running gulp.

**Comment by isigmund** [comment]
Ok I understand the goal, but I'm not sure if I have done this correctly. Its kind of the first time I work with gulp. Can you take a short look at the attached gulpfile to check if I am on the right track. It works for me here in my dev environment, but I am not sure if its the right way to do for delivery. I based the additions that I made to what was there for the codemirror stuff.
Thanks
    Ingo
[gulpfile.js.txt](https://github.com/openhab/org.openhab.ui.habpanel/files/527836/gulpfile.js.txt)

**Comment by ghys** [comment]
You don't have to add additional tasks, just add 
`        'bower_components/angular-ui-clock/dist/angular-clock.min.js',`
in the vendor-js task below
`        'bower_components/oclazyload/dist/ocLazyLoad.min.js',`
and in the vendor/vendor.scss file (sorry I was wrong before)
`@import "../bower_components/angular-ui-clock/dist/angular-clock";`
below
`@import "../bower_components/angularjs-slider/dist/rzslider";`

`gulp sass` and `gulp` and it should do the trick.
