### ISSUE TITLE
Behavior of HOME + BACK Button

### ISSUE THREAD

**Issue by s-simma** [openhab/org.openhab.ui.habpanel#42]
On my iPads(2,3), with the latest version from github installed, pressing the "home-button" doesn't take me to the home-screen any more. To go to the home-screen i have to click on  "home-button" AND "back-button" afterwards or vice versa. A double-click one one of them works as well. On the PC-Desktop it works as expected.
This was not the case with the last version.
Does anybody else has this effect ?
Thank you very much to have scrolling back again !

**Comment by mdilger** [comment]
I am running openHAB build #526 which I believe is up to date with what is on github for habpanel.

Everything looks OK on my iPad 2 and iPad Pro.

That said, I have seen some strange behaviour in the past with the "back button", but all looks normal at present.

**Comment by s-simma** [comment]
@mdilger 
The latest HABpanel version has text to speech settings on the home setting page. Is this what you have?

**Comment by mdilger** [comment]
Yes, I have that version.  I have another issue that I have not reported yet re: the voice selection but the "back" and "home" buttons seem to be Ok.

**Comment by s-simma** [comment]
Strange, anyway with a double-click i come back to home.
Regarding text to voice:
If i switchs the HABpanel application to background and then to foreground back again, the voice output will stop until i go to the setting page and press the "Test" button. Then voice output continues.
On the desktop-PC no problems so far.

**Comment by mdilger** [comment]
My issue is with the voice selection.  In the case of the iPad pro, I get multiple voice options per language (en-AU) for example, but if I choose the second or third option it always defaults to the first voice on the list for that language.  Same if i choose en-GB voices.

**Comment by s-simma** [comment]
On my iOs 10 the language selection gives the same result you have.
Arthur (en-GB)  or Martha (en-GB) allways gives Arthur (en-GB), which is the first "en-GB"

**Comment by ghys** [comment]
Actually a encountered this issue on a borrowed iPad as well a few days ago. I did some tuning then and just merged them with #43.

**Comment by s-simma** [comment]
Double click problem solved. Thanks.
Realy fantastic !!!!
As i mentioned, switching HABpanel from forground to background and back to forground will break the text to voice. After going to "setting and play the test text it works again.
Isn't it possible to call this function with an empty string if application jumps to foreground ?

**Comment by ghys** [comment]
Don't know, will have to take a look. It's actually the same code during item change and when hitting the test button.
