### ISSUE TITLE
Text to voice error

### ISSUE THREAD

**Issue by s-simma** [openhab/org.openhab.ui.habpanel#45]
On destop-PC:
Every time after starting HABpanel in the browser the first text to voice message gives the following error in the browser debugger. All the following work fine. 
![screenshot - 14_10](https://cloud.githubusercontent.com/assets/15436483/19397440/2a0bec02-9248-11e6-8809-15fe5045e9f9.jpg)

**Comment by ghys** [comment]
Confirmed. I'll have a fix asap.
