### ISSUE TITLE
Knob Widget: Add color ranges

### ISSUE THREAD

**Issue by isigmund** [openhab/org.openhab.ui.habpanel#52]
I am working on an enhancement to the knob widget to allow defining ranges and asssign a color to each range. When the value is inside one of the ranges the color of the Knob widget and the color of the vaule changes accordingly.
Additionally if the tron style is used the tron arc would show the color ranges as well to indicate where the color change does happen.
I took this idea from [grafana](http://grafana.org/) which has a similar concept.

In HabPanel it would look similar to this:
![image](https://cloud.githubusercontent.com/assets/5901482/19621449/873fcc9a-9892-11e6-8556-08b1dd8ddef1.png)
(taken from my current HabPanel where I use an template widget with an iframe to embedd an grafana chart - really slow thats the reason why I want to replace this with native HabPanel functionality)

To define the ranges (up to 5) I plan to enhance the settings dialog with an additional tab.

Let me know what you think.

Take care
   Ingo
##

**Comment by ghys** [comment]
Looks nice!
Do you intend to fork ng-knob? I don't see it having this feature. For a change this significant we would have to come up with a way to keep forked external dependencies manageable.

I don't necessarily mind the new tab too much but I still tried to limit them because for devices in portrait mode it would wrap to a second line (which is ugly).

**Comment by isigmund** [comment]
@ghys I have forked ng-knob and added the functionality to color the valueBar and the text according to the value. So I was thinking after that pull request to ng-knob has been integrated we can refer to the newer version that has then the ranges functionality. Wouldn't that work ? 

Here is how the definition of the ranges does look like in the ng-knob (its almost finished, I am just missing to color the tron bar according to the ranges):
![image](https://cloud.githubusercontent.com/assets/5901482/19628478/cdcd2a28-995e-11e6-8ef9-939ac1ba7710.png)

**Comment by isigmund** [comment]
In regards to the additional tab. Technically the ranges belong to the bar, bit the Bar tab already has a lot of color setting which makes it quite big already. If I add the ranges there we would have even more color settings. That was the reason for me to decide for an additional tab.
Another option would be to use a bootstrap "well" control to display the color and clicking on the well would open the color settings you already use in an additional dialog. This would have the benefit that all other setting dialogs that have color settings would become smaller as well (no scrolling on smaller screens).
Let me know what you thing about this.

**Comment by isigmund** [comment]
I am done with my changes on ng-knob and issued a PR. Hope this will be merged soon. 
If you want to see it in action please visit [](https://isigmund.github.io/ng-knob/)

**Comment by ghys** [comment]
Cool. I myself needed to fork it to add an "onEnd" callback and it never got merged - see the bower file actually points to my fork. Seems like @RadMie is not working actively on ng-knob anymore.

Since my change is necessary for HABPanel, and my fork is the one used as the bower dependency, if you don't receive a response from upstream I guess you could submit the PR to my repository instead.

**Comment by isigmund** [comment]
@ghys  I was finally able to complete the development for the color ranges of the knob widget. I am ready to create the PR but I first wanted to discuss the settings UI with you to see if you agree. 
So first here is how some example knobs look like with the color ranges:
![image](https://cloud.githubusercontent.com/assets/5901482/21268994/3d412e64-c3b1-11e6-9d44-86ddcd6a76a2.png)

The settings dialog for the ranges looks like this:
![image](https://cloud.githubusercontent.com/assets/5901482/21269036/6184b6d8-c3b1-11e6-9fc2-66531e5f16fe.png)

The first checkbox enables or disables the ranges. The second one does control if the text color should match the bar or of if it should just use the text color set on the Misc tab

For each range the accordeon shows this:
![image](https://cloud.githubusercontent.com/assets/5901482/21269112/b43fb404-c3b1-11e6-919c-e22f60fb2c51.png)

I have by purpose added a text field for the color in addition to the color picker. This adds the possibility to set other colors as the webcolorpicker allows. With this its possible to create nice gradients like in the second example above.

Let me know what you think....

Take care
   Ingo

**Comment by ghys** [comment]
Hi @isigmund 
Sorry for not responding sooner, I wasn't much available this weekend. 😉 
Your PR is looking great! I also had the same idea about the color pickers (allowing a text entry option) actually, so it's something that could even be included in the color picker directive itself and be available everywhere.

I'll have a closer look ASAP and it's going to be merged in the next few days.
Thanks!

**Comment by isigmund** [comment]
Closed with PR #102

**Comment by LeDumpier** [comment]
Hi @isigmund 

Great looking widget thanks.

Would you mind posting the colour values for the blue-to-red temperature widget as per your example?

![image](https://cloud.githubusercontent.com/assets/19993783/26723284/151020aa-4794-11e7-9ff0-50ee8c240234.png)

Many thanks in advance,

Craig

**Comment by isigmund** [comment]
Hello,

I dont think I have the exact values for this anymore, But I used http://www.perbang.dk/rgbgradient/ <http://www.perbang.dk/rgbgradient/> to generate them. On this site you can define a starting and an endcolor, and a number of steps to generate a gradient. I used the HSV inverse (it looked most natural).

hope that helped.

Take care
    Ingo
