### ISSUE TITLE
Select json from a http server

### ISSUE THREAD

**Issue by korg1000** [openhab/org.openhab.ui.habpanel#59]
There is any chance to choose a previously saved configuration json by a http url?
My idea is to save the json and load this from a url.
I use OH 1.8.x.
Or wich file is the 'loading json' function, so i could change it myself?
Thanks

**Comment by ghys** [comment]
Persistence of settings including local storage is in `web/app/services/persistence.service.js`
The openHAB 2 service configuration REST API client is in `web/app/services/openhab.service.js`
