### ISSUE TITLE
Old issue OH 1.8.x: sometimes the item dont update

### ISSUE THREAD

**Issue by korg1000** [openhab/org.openhab.ui.habpanel#60]
I think the problem is with OH (when i restart OH the atmosphere websocket start working again).
So, there is a way to do a second option: update the items via rest after a X seconds besides the websocket?
Thanks

**Comment by ghys** [comment]
Closing due to lack of interest 🙄 
Besides, this repo doesn't support OH1 anymore - see https://community.openhab.org/t/habpanel-openhab-1/20587
