### ISSUE TITLE
webaudio not working on Android browsers

### ISSUE THREAD

**Issue by tavalin** [openhab/org.openhab.ui.habpanel#65]
`audio play webaudio doorbell.mp3` works sucessfully on my PC using Firefox and Chrome.

I'd like to be able to use webaudio for wall mounted tablets - the idea is actually a multi room doorbell - however webaudio does not seem to work on Android in either the native Samsung browser or Chrome.  Any ideas?

Conversely, webaudio works through Paper UI on my Android devices.

**Comment by ghys** [comment]
I confirmed it works with Chrome on my Android tablet at least with #56 applied.
So I'm closing this, wait for the next build before updating and testing again (https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/org.openhab.ui$org.openhab.ui.habpanel/), and feel free to reopen if you still have this issue.
