### ISSUE TITLE
widget-icon not updating

### ISSUE THREAD

**Issue by xsherlockpl** [openhab/org.openhab.ui.habpanel#70]
It seems that  widget icon is not updating when used in the templates. It is correct on the first load of the panel and does change after the first use, but that's it. The button continue to does work but will not update the state of the icon. In my case the gLights_B is a group of the lights and I use a button to pass OFF in order to do a master OFF only switch.

```
<button class="test" 
        style= "border: none; background: rgba(0,0,0,0); outline:none; " 
        ng-click="sendCmd('gLights_B', 'OFF')"> 
	<widget-icon iconset="'smarthome-set'" icon="'power-button'" size="100" state="itemValue('gLights_B')" />          
</button>
```
Do you see that too?

**Comment by ghys** [comment]
I'll have a look at this soon.

**Comment by ghys** [comment]
Maybe that's related to the subsequent changes being pushed as a SSE `ItemStateChangedEvent` which were ignored, only `ItemStateEvent` was considered - #86 remedies that.
It solves a similar problem with shutter icons in the demo setup.
Can you verify if that takes care of your problem as well?

**Comment by xsherlockpl** [comment]
I did an upgrade to my openhab2 install with apt-get update/upgrade and the bug is still there.
Not sure if the if the HABpanel #86 is already in  OH2 #641, how do I check that?

**Comment by ghys** [comment]
Can you check in the Javascript console whether the state update is actually received? (You should see a line "Updating gLights_B state from OFF to ON" or similar). If not then openHAB is probably not sending the update for some reason.

**Comment by xsherlockpl** [comment]
I see the comand being sent on the button press but when I switch one of the lights in the group back on (B_office_rel4_office_wall) I do not see the update to the group coming in.

![2016-12-21 22_03_52-habpanel](https://cloud.githubusercontent.com/assets/23699880/21406059/e22a0754-c7c9-11e6-88a1-9bdbdca3defc.png)

How do I check which commit of the HABpanel I run?  I did reinstall the habpanel from PaperUI but not sure if that is enought to get latest version.

**Comment by ghys** [comment]
Well, that's a bummer. By other UIs you mean Basic UI and Classic UI, or Paper UI too? Because Paper UI uses the same mechanism as HABPanel to receive updates (SSE), so it works the HABPanel implementation would still be to blame.
What you can maybe try is to have a look at the raw event stream - in the Network tab of the developer tools look for a line named "events", you will then have a EventStream tab with all the messages arriving. If you don't see an update for your item, this means openHAB is not sending it.

**Comment by xsherlockpl** [comment]
It works with basicUI, paperUI does not allow for a control  of group switches  yet.

I see there something called : `GroupItemStateChangedEvent`  right after the change to the indviudal switch so the changes for the group items might be pushed diffrently from the openHAB

Anyway Here is my console view. Maybe you can figureout something from it.
![2016-12-22 10_34_58-the grand tour s01e03 1080p webrip x264-deflate rarbg](https://cloud.githubusercontent.com/assets/23699880/21421430/1a18326c-c833-11e6-913a-b04f0bf361ad.png)

**Comment by ghys** [comment]
That's interesting... I didn't know there was a `GroupItemStateChangedEvent`, but it seems to reflect the change of a particular item within a group, not the calculated state of the group itself... I was expecting an state change event for the actual group item - it doesn't seem to be the case here. Perhaps it's not handled at all and the GUI client itself is supposed to derive the state of the group from the state of its members.

Maybe an issue on ESH asking for an explanation about the handling of SSE events and groups could provide some insight.

**Comment by andreasgebauer** [comment]
I had a look at the ESH code regarding the state of the GroupItemStateChangedEvent. As far is I understood the calculated state of the Group is wrapped in this type of event rather than the state of an item of the group.

Excerpt from org.eclipse.smarthome.core.items.GroupItem:
```
public void stateUpdated(Item item, State state) {
  State oldState = this.state;
  setState(function.calculate(members));
  if (!oldState.equals(this.state)) {
    sendGroupStateChangedEvent(item.getName(), this.state, oldState);
  }
}
```

The created event is then sent as SSE via the ESH event bus. And that's actually what we receive on the client side.

**Comment by xsherlockpl** [comment]
Is that a change required in the HABpanel or in OH2 code?

**Comment by andreasgebauer** [comment]
The GroupItemStateChangedEvent is sent via SSE. In my opinion it needs to be supported by habpanel.

**Comment by ghys** [comment]
@andreasgebauer thanks for figuring it out!

Using the demo items, when I turn all lights off then turn one light back on (_Light_FF_Corridor_Ceiling_) I receive these events:

```
{"topic":"smarthome/items/Light_FF_Corridor_Ceiling/state","payload":"{\"type\":\"OnOffType\",\"value\":\"ON\"}","type":"ItemStateEvent"}	
17:00:21.283
{"topic":"smarthome/items/Light_FF_Corridor_Ceiling/statechanged","payload":"{\"type\":\"OnOffType\",\"value\":\"ON\",\"oldType\":\"OnOffType\",\"oldValue\":\"OFF\"}","type":"ItemStateChangedEvent"}	
17:00:21.299
{"topic":"smarthome/items/FF_Corridor/Light_FF_Corridor_Ceiling/statechanged","payload":"{\"type\":\"OnOffType\",\"value\":\"ON\",\"oldType\":\"OnOffType\",\"oldValue\":\"OFF\"}","type":"GroupItemStateChangedEvent"}	
17:00:21.301
{"topic":"smarthome/items/Lights/Light_FF_Corridor_Ceiling/statechanged","payload":"{\"type\":\"OnOffType\",\"value\":\"ON\",\"oldType\":\"OnOffType\",\"oldValue\":\"OFF\"}","type":"GroupItemStateChangedEvent"}
```

As I now understand it, those last two `GroupItemStateChangedEvent` events are reporting the new state of the **group** (3rd part of the topic), not the group member (4th part)? The fact that the item *causing the change* in the state of the group appeared was confusing.

So indeed I'll assume the group name should be parsed from the 3rd part of the topic and its state should be updated when receiving a `GroupItemStateChangedEvent`.

**Comment by andreasgebauer** [comment]
I can confirm that the group which changes state is 3rd part of the topic, the group member which caused this change is the 4th part.

**Comment by ghys** [comment]
@andreasgebauer @xsherlockpl this really simple fix in #137 seems to take care of it then (tested successfully with the demo setup).
Feel free to reopen if the problem persists.
Thanks!

**Comment by xsherlockpl** [comment]
just to confirm that fixed the poblem.

**Comment by xeusito** [comment]
Could you please tell me where to find the openhab.service.js file that needs to be changed? 
I made the changes in the one i found on /var/lib/openhab2/tmp/mvn/org/openhab/ui/org.openhab.ui.habpanel/2.0.0/org.openhab.ui.habpanel-2.0.0.jar file but according to the browser console it doesn't seem to pick up the change.
Thanks

**Comment by ghys** [comment]
Just use a recent snapshot build, no need to do that yourself too.
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ or
https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/org.openhab.ui$org.openhab.ui.habpanel/
if you just want to upgrade HABPanel. Check the docs and/or community.openhab.org for the upgrade procedure.

**Comment by xeusito** [comment]
Thanks! That worked perfectly!
