### ISSUE TITLE
Live updates for interactive charts

### ISSUE THREAD

**Issue by andreasgebauer** [openhab/org.openhab.ui.habpanel#74]
When an update of an item defines as a series of an interactive chart comes in the chart should be updated.

**Comment by kubawolanin** [comment]
Hey @andreasgebauer. Thank you for contributing!
Just for the reference: implemented by @andreasgebauer in #77

**Comment by FutureCow** [comment]
Would it also be possible to use switch and contact inside a chart?
Because OpenHAB REST is using OPEN and CLOSED, ON and OFF. So the chart gives an error (of course): NaN

So change OPEN to 1 en CLOSED to 0 inside the chart.
