### ISSUE TITLE
Provide an dashboard configuration for the demo setup

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/org.openhab.ui.habpanel#78]
openHAB comes with a demo setup, which defines items, sitemap and rules and can be used to demonstrate the features of openHAB. It is e.g. also used for our demo server at http://demo.openhab.org:8080/start/index.

I would very much love to have HABPanel included in it - at the moment, HABPanel is shown empty: http://demo.openhab.org:8080/habpanel/index.html#/

It would be great to have a read-only configuration defined that shows the features of HABPanel.
I can help integrating it into the demo setup, if someone else would create the dashboard configuration. Let me know what you think!

**Comment by ghys** [comment]
Great to see it on the demo server! I see several people have already found the way to save stuff :smile: 

A "demo mode" is doable, it would but load a pre-made static configuration, from a JSON file for example. Perhaps prevent any persistent storage too and reset on each visit. To enable it I see two options:
1) with an additional switch in [ESH-INF/config/config.xml](https://github.com/openhab/org.openhab.ui.habpanel/blob/master/ESH-INF/config/config.xml). But it would have to be set in advance when deploying the demo server, and it can be disabled with a POST to the REST API.
2) detect the demo items when loading them and enter the demo mode accordingly. With this approach, it would be more difficult to go back to normal on a local instance (apart from switching to the standard or minimal base package).

**Comment by mattwire** [comment]
A readonly configuration file would also be really useful for deploying as a "production" or "locked down" panel.  Something like: if (habpanel.json exists), load it readonly and disable editing.
And you can create the json file by exporting from an editable habpanel...

**Comment by kaikreuzer** [comment]
My reason to enter this issue was more to ask you to design a nice dashboard based on the available items rather than think of a special "demo mode". :-)

I would simply add this JSON as a configuration of the HABPanel bundle on the runtime, so it would be automatically available.
Question: If no dashboard is defined in the browser storage, does HABPanel automatically pick up the dashboards that are stored on the runtime? If not, would it make sense to change it that way?

To restrict editing (and thus cover @mattwire's request), it might be easiest to add a property within the JSON which says whether a dashboard is read-only or not. You could even offer UI support to add this flag, but for a start it would be enough to manually add it to the JSON.

**Comment by ghys** [comment]
> My reason to enter this issue was more to ask you to design a nice dashboard based on the available items rather than think of a special "demo mode". :-)

I know :) I will make one, of course.
Nonetheless, it might be relevant to prevent random users to alter the configuration on demo.openhab.org (or rather allow them to play with it but don't have any kind of permanent storage)

> Question: If no dashboard is defined in the browser storage, does HABPanel automatically pick up the dashboards that are stored on the runtime? If not, would it make sense to change it that way?

It doesn't. You have to go to the settings and choose a "panel configuration" to use, several of which may be stored server-side. It does make sense to maybe make the user choose one of these panel configurations if some are detected when starting fresh.

> To restrict editing (and thus cover @mattwire's request), it might be easiest to add a property within the JSON which says whether a dashboard is read-only or not. You could even offer UI support to add this flag, but for a start it would be enough to manually add it to the JSON.

For the record, it already exists - for all of your HABPanels.

You can configure it in Paper UI for instance:

![image](https://cloud.githubusercontent.com/assets/2004147/20887129/b01403b4-baf9-11e6-8ee5-cf4b62418dcd.png)

The rationale behind this is: when you're hacking around you disable it and, and re-enable it when you're in "production mode" and don't want your house's end users to access the editing features.

**Comment by kaikreuzer** [comment]
> It does make sense to maybe make the user choose one of these panel configurations if some are detected when starting fresh.

My idea was to say: If there is only one configuration available, it is likely that the user wants to see this - so it should be displayed right away.
Maybe it could also have a setting like the "defaultSitemap" in the Basic UI, i.e. the dashboard to open when launching.

> For the record, it already exists - for all of your HABPanels.

Perfect, I knew I had seen this already somewhere. Yeah, that's just what we need!

**Comment by ghys** [comment]
@kaikreuzer alright, I made a rather comprehensive set of dashboards showing most of HABPanel's end user features and using the demo package's items. You can check it out by going to http://demo.openhab.org:8080/habpanel/index.html#/settings and choosing the "demo" panel configuration. Size and aspect ratio are important for the dashboards to display correctly - is it optimized for iPad-like tablets in landscape mode:

![image](https://cloud.githubusercontent.com/assets/2004147/20947588/308457bc-bc10-11e6-85d2-6a87b9d76f43.png)

![image](https://cloud.githubusercontent.com/assets/2004147/20947550/fe2d7b9a-bc0f-11e6-8b38-ccaba8f2c1e3.png)

![image](https://cloud.githubusercontent.com/assets/2004147/20947647/6d612fac-bc10-11e6-80bb-d982673d3856.png)

![image](https://cloud.githubusercontent.com/assets/2004147/20947694/9f98deb6-bc10-11e6-995b-da1cceb0ba3e.png)

...and so on.


The configuration JSON is pasted here:
https://pastebin.ubuntu.com/23590783/
You can restore it using this screen:
http://demo.openhab.org:8080/habpanel/index.html#/settings/localconfig
A PUT to http://demo.openhab.org:8089/rest/services/org.openhab.ui.habpanel/config with the following in the body:
https://pastebin.ubuntu.com/23590866/
should reset it.

I'll come up with something to show it from the beginning and prevent it to be edited.
Let me know if it's what you had in mind!

**Comment by kaikreuzer** [comment]
Wow, this is gorgeous, thanks!

> I'll come up with something to show it from the beginning and prevent it to be edited.

Looking forward to it - I will then include it directly in the demo setup as well!

**Comment by ghys** [comment]
@kaikreuzer the PR above (#85) should do the trick - just set `initialPanelConfig` to `demo` and `lockEditing` to `true` like below, and the demo panel config will be presented by default if none is set.

![image](https://cloud.githubusercontent.com/assets/2004147/21083457/50f581a8-bff1-11e6-90af-d3660a3307f6.png)

**Comment by kaikreuzer** [comment]
I'll try that, thanks!

**Comment by kaikreuzer** [comment]
Tried, but I now see this screen only:

<img width="821" alt="screen shot 2016-12-12 at 10 42 39" src="https://cloud.githubusercontent.com/assets/3244965/21094546/bb0b14fc-c057-11e6-84f7-36f775db4d6f.png">

Check it at http://demo.openhab.org:8080/habpanel/index.html#/ yourself. Any advice?

**Comment by ghys** [comment]
Yes, it was because the "panelsRegistry" was set to an array of dashboards, i.e.:
`"panelsRegistry": "[ { "id": "first-floor", "name": "First Floor", ... } ]",`
which is wrong, it actually is a map of those arrays, like so:
`"panelsRegistry": "{ "demo": { "updatedTime": "...", "dashboards": [ { "id": "first-floor", "name": "First Floor", ... } ] }",`
You probably copied the configuration from the local configuration editor which shows only the *local* panel configuration, not all of them.

I made the correction on the demo server (!) using Swagger with this body:
http://pastebin.ubuntu.com/23618294/

And it now seems to work! :)

**Comment by kaikreuzer** [comment]
Wonderful, thanks 👍

**Comment by kubawolanin** [comment]
Demo dashboards seem to be gone?
http://demo.openhab.org:8080/habpanel/index.html#/settings

**Comment by kaikreuzer** [comment]
Seems somebody played around last night and disabled the lock of the panel - I have restored it again!

**Comment by ghys** [comment]
Thanks for fixing it @kaikreuzer (and @kubawolanin for the report).
Guess this can happen from time to time... It's easy to restore the intended config, so if it doesn't occur too often I wouldn't worry about it, but if vandalism becomes a problem maybe the demo server should be put behind a reverse proxy blocking all non-GET REST API requests? (except `POST /items/{itemname}`)

**Comment by kaikreuzer** [comment]
>  blocking all non-GET REST API requests? 

Not a good idea, because you wouldn't be able to switch a single item anymore - the demo server would be a bit too read-only then :-)

Vandalism isn't really a problem, restoring the setup isn't hard.

**Comment by ghys** [comment]
> you wouldn't be able to switch a single item anymore

Yes, this was the one exception I made :) - `POST /items/{itemname}`
I was thinking as well about potentially being able to `DELETE /things/{thingUID}` (or items) and the like, but you're right, it's only a demo :)

**Comment by kaikreuzer** [comment]
I am still waiting for having an authorization feature available and active in openHAB, then I would definitely use it for the demo server as well. Not keen on setting up any reverse proxy with a specific configuration, though.

**Comment by kaikreuzer** [comment]
Thanks @ghys! I am also quite familiar with OAuth2 and think this might be a good option for openHAB (knowing that it will mean quite some effort as we will have to adjust the native apps as well for that and ideally myopenhab/openhab-cloud at the same time).

eclipse/smarthome#2587 has been designed in a way that the solutions are free to choose whatever auth mechanism they want - imho, we should not tightly couple it to OAuth2.

For the moment, I actually got stuck much much earlier: I even failed using eclipse/smarthome#2587 in any simple way (doing BasicAuth) in openHAB - see [some details here](https://github.com/eclipse/smarthome/issues/579#issuecomment-272005222).
Imho, this needs to be solved first, before going into any more detailed concepts - without a foundation, it would all be just nice theory...

**Comment by marziman** [comment]
@ghys come over to https://github.com/eclipse/smarthome/issues/579#issuecomment-272005222

Heiko & me are actively on this topic and trying to coordinate this topic to get it done.
We are currently collecting the ideas, requirements and views of all interested parties, so feel free to join the discussion. We will heavily push this topic since we will need OAuth on home-iX side.
So we are hoping to make this happen by a joined-forces approach with the community, Qivicon colleagues and us on home-iX side. 
I totally agree, we should not tightly couple things, but this doesnt mean that the basics to have OAuth shouldnt be there within ESH, so that interested people (I would say everybody) can use/extend it for OAuth. We should make that a first citizen from my point of view, cause it is a really really well knonw and established way to secure APIs and do even more RBAC stuff, which will be great for OH too.

BR Mehmet
