### ISSUE TITLE
Searchable selectbox for items

### ISSUE THREAD

**Issue by lewie** [openhab/org.openhab.ui.habpanel#82]
When there are a lot of Items in openHAB it is very difficult to scroll and find.

So thought about a searchable selectbox like:
[Examples here](http://angular-ui.github.io/ui-select/demo-append-to-body.html)
[Source](https://github.com/angular-ui/ui-select)

@ghys, what do you think? :-)

**Comment by lewie** [comment]
Oh, found filterable dropdown within the Weather Widget:
https://github.com/openhab/org.openhab.ui.habpanel/pull/72


Thank You @kubawolanin. So I pushed it.

**Comment by kubawolanin** [comment]
Yep, and I've also already submitted an issue :) #27 
Hopefully I will find some time to cleanup the pull request this weekend.

**Comment by ghys** [comment]
Yes, I wasn't too sure about that initially (I figured the native implementations of select boxes were always better especially on mobile devices; better scrolling etc.), but the search functionality is so useful it will definitely will be merged. Hang on a little while longer. :)
