### ISSUE TITLE
Multiseries chart does not render if one series has no data in period

### ISSUE THREAD

**Issue by stoikan** [openhab/org.openhab.ui.habpanel#83]
To start with I must say that I absolutely love Habpanel and all the action in this project right now!

I was very happy when the support for several series was added in the chart widget. It was the turning point for me which made me migrate from the basicui to habpanel.

It seems however that the chart does not render correctly if you have several series in which (at least) one series does not have any data points in the period you try to chart.

In my case I chart all my motion sensors (0 and 1) in the same graph to illustrate the movement in my house. If one sensor has no change within the chart period the graph does not work. A workaround would be to persist the sensor values every 15 minutes or so but I would rather only want to persist actual changes.

Example of a non working chart
<img width="581" alt="screen shot 2016-12-07 at 08 48 12" src="https://cloud.githubusercontent.com/assets/7426810/20959207/15116be2-bc5a-11e6-8e5c-21afcac8e5c0.png">

Example of a working chart
<img width="573" alt="screen shot 2016-12-07 at 08 48 55" src="https://cloud.githubusercontent.com/assets/7426810/20959208/15121f2e-bc5a-11e6-9467-632bbdae0de4.png">

**Comment by ghys** [comment]
I'm aware of that :)
Thanks for the report nonetheless.
