### ISSUE TITLE
Add possibility to copy existing widgets

### ISSUE THREAD

**Issue by dominicdesu** [openhab/org.openhab.ui.habpanel#9]
Hi,
would be a nice feature in my opinion to be able to copy an existing widget. 
Sometimes one has very similar items which also should look the same in HABpanel (e.g. color of buttons). Would be much easier if I could just copy an existing widget configuration and change the linked OH item.
##

**Comment by neohusky** [comment]
I was thinking the same thing the other day. Great idea.

**Comment by digiltd** [comment]
Im sure it will come, but in the meantime if you wanted a workaround, you can easily take the json, plop it in a text editor and prettify it. Then copy and paste widgets to your hearts content :) :

**Comment by isigmund** [comment]
I started to work on this. See comments on #10
